#!/usr/bin/env bash
# compile-runtime-instructions-selftest.sh
#
# Verifies that scripts/compile-runtime-instructions.sh emits all generated
# runtime targets deterministically and that --check detects drift.
#
# Coverage:
#   - --target all runs and writes the four generated targets + two manifest files.
#   - --check exits 0 when targets are in sync.
#   - --check exits non-zero when a target has been mutated by hand.
#
# This selftest is self-contained: it operates on a temp copy of the live
# workspace so it does not leave drift behind in the real repo.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
COMPILER="$ROOT/scripts/compile-runtime-instructions.sh"

[[ -f "$COMPILER" ]] || { echo "FAIL: compiler not found: $COMPILER" >&2; exit 1; }

# Live --check must pass when invoked against the committed workspace.
if ! bash "$COMPILER" --check >/tmp/dp230-t18-compile-runtime-check.out 2>&1; then
  cat /tmp/dp230-t18-compile-runtime-check.out >&2
  echo "FAIL: live workspace targets out of sync. Run 'bash scripts/compile-runtime-instructions.sh' to regenerate." >&2
  exit 1
fi

# Sanity: each generated target must mention the canonical generator banner.
for target in CLAUDE.md AGENTS.md .codex/AGENTS.md .github/copilot-instructions.md; do
  if ! grep -q "Generated by .scripts/compile-runtime-instructions.sh." "$ROOT/$target"; then
    echo "FAIL: missing generator banner in $target" >&2
    exit 1
  fi
done

# Sanity: manifest files exist and list source files.
for manifest in .codex/.generated/rules-manifest.txt .github/.generated/copilot-rules-manifest.txt; do
  if [[ ! -f "$ROOT/$manifest" ]]; then
    echo "FAIL: missing manifest file: $manifest" >&2
    exit 1
  fi
  if ! grep -q "^\[sha256\]$" "$ROOT/$manifest"; then
    echo "FAIL: manifest $manifest missing [sha256] section" >&2
    exit 1
  fi
done

# Drift detection: copy the workspace to a tmp dir, mutate CLAUDE.md, and verify
# --check fails. We rebuild the script invocation against the temp ROOT_DIR by
# running the script copy directly (it derives ROOT_DIR from its own location).
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

# Stage minimal subtree required by the compiler.
mkdir -p "$TMP_DIR/scripts" "$TMP_DIR/.claude/instructions/runtime" \
  "$TMP_DIR/.claude/instructions/core" "$TMP_DIR/.claude/rules" \
  "$TMP_DIR/.codex/.generated" "$TMP_DIR/.github/.generated"
cp "$ROOT/scripts/compile-runtime-instructions.sh" "$TMP_DIR/scripts/"
cp "$ROOT/.claude/instructions/manifest.yaml" "$TMP_DIR/.claude/instructions/"
cp "$ROOT/.claude/instructions/core/bootstrap.md" "$TMP_DIR/.claude/instructions/core/"
cp "$ROOT/.claude/instructions/runtime/claude.md" "$TMP_DIR/.claude/instructions/runtime/"
cp "$ROOT/.claude/instructions/runtime/codex.md" "$TMP_DIR/.claude/instructions/runtime/"
cp "$ROOT/.claude/instructions/runtime/copilot.md" "$TMP_DIR/.claude/instructions/runtime/"
# Copy universal rule files so emit_rule_index produces a stable listing.
find "$ROOT/.claude/rules" -maxdepth 1 -type f -name '*.md' -exec cp {} "$TMP_DIR/.claude/rules/" \;

# First regenerate everything in the tmp ROOT.
bash "$TMP_DIR/scripts/compile-runtime-instructions.sh" >/tmp/dp230-t18-compile-runtime-generate.out 2>&1
# A fresh --check on tmp should pass.
bash "$TMP_DIR/scripts/compile-runtime-instructions.sh" --check >/tmp/dp230-t18-compile-runtime-check-fresh.out 2>&1

# Drift the tmp CLAUDE.md and confirm --check fails.
printf '%s\n' "HAND-EDITED CONTENT" >> "$TMP_DIR/CLAUDE.md"
if bash "$TMP_DIR/scripts/compile-runtime-instructions.sh" --check >/tmp/dp230-t18-compile-runtime-check-drift.out 2>&1; then
  echo "FAIL: --check did not detect hand-edited drift in CLAUDE.md" >&2
  exit 1
fi

echo "PASS: compile-runtime-instructions selftest"
