#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRIPT="$ROOT/scripts/memory-hygiene-tiering.py"
FIXTURES="$ROOT/scripts/selftests/fixtures/memory-hygiene-emit-index"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fail() { echo "FAIL: $*" >&2; exit 1; }

# --- Test 1: help surfaces --emit-index flag --------------------------------
python3 "$SCRIPT" --help 2>&1 | grep -q -- '--emit-index' \
  || fail "--emit-index missing from --help output"

# --- Test 2: roundtrip on hand-maintained MEMORY.md is byte-equal -----------
case_dir="$TMP/case-roundtrip"
cp -R "$FIXTURES/case-roundtrip/memory" "$case_dir"
cp "$FIXTURES/case-roundtrip/memory/MEMORY.md" "$TMP/roundtrip-baseline.md"
python3 "$SCRIPT" --emit-index --memory-dir "$case_dir" --today 2026-05-20 >/dev/null
diff "$TMP/roundtrip-baseline.md" "$case_dir/MEMORY.md" \
  || fail "case-roundtrip output not byte-equal to input"

# --- Test 3: legacy footer is preserved as suffix annotation ---------------
case_dir="$TMP/case-legacy-footer"
cp -R "$FIXTURES/case-legacy-footer/memory" "$case_dir"
python3 "$SCRIPT" --emit-index --memory-dir "$case_dir" --today 2026-05-20 >/dev/null
diff "$FIXTURES/case-legacy-footer/expected.md" "$case_dir/MEMORY.md" \
  || fail "case-legacy-footer output does not match expected"

# --- Test 4: prefix + suffix annotation preserved byte-equal ---------------
case_dir="$TMP/case-annotation"
cp -R "$FIXTURES/case-annotation/memory" "$case_dir"
cp "$FIXTURES/case-annotation/memory/MEMORY.md" "$TMP/annotation-baseline.md"
python3 "$SCRIPT" --emit-index --memory-dir "$case_dir" --today 2026-05-20 >/dev/null
diff "$TMP/annotation-baseline.md" "$case_dir/MEMORY.md" \
  || fail "case-annotation output not byte-equal (annotation drift)"

# --- Test 5: generated marker present in output ----------------------------
grep -q 'generated by memory-hygiene-tiering.py --emit-index' "$case_dir/MEMORY.md" \
  || fail "generated marker missing from emit-index output"
grep -q 'end: memory-index generated block' "$case_dir/MEMORY.md" \
  || fail "end marker missing from emit-index output"

# --- Test 6: --dry-run emits unified diff and does NOT modify the file -----
case_dir="$TMP/case-dry-run"
cp -R "$FIXTURES/case-legacy-footer/memory" "$case_dir"
cp "$FIXTURES/case-legacy-footer/memory/MEMORY.md" "$TMP/dry-run-baseline.md"
diff_out="$(python3 "$SCRIPT" --emit-index --dry-run --memory-dir "$case_dir" --today 2026-05-20)"
echo "$diff_out" | grep -q '^@@ ' \
  || fail "--dry-run did not emit unified diff hunks"
diff "$TMP/dry-run-baseline.md" "$case_dir/MEMORY.md" \
  || fail "--dry-run mutated MEMORY.md (must be no-write)"

# --- Test 7: --dry-run on already-current MEMORY.md reports no changes -----
case_dir="$TMP/case-dry-run-noop"
cp -R "$FIXTURES/case-roundtrip/memory" "$case_dir"
noop_out="$(python3 "$SCRIPT" --emit-index --dry-run --memory-dir "$case_dir" --today 2026-05-20)"
echo "$noop_out" | grep -q 'no changes' \
  || fail "--dry-run on current MEMORY.md did not report no changes"

# --- Test 8: --dry-run cannot be combined with positional mode -------------
case_dir="$TMP/case-conflict"
cp -R "$FIXTURES/case-roundtrip/memory" "$case_dir"
if python3 "$SCRIPT" --emit-index dry-run --memory-dir "$case_dir" --today 2026-05-20 >/dev/null 2>&1; then
  fail "--emit-index combined with positional mode should fail"
fi

# --- Test 9: Hot ordering — last_triggered desc, no-lt at tail --------------
case_dir="$TMP/case-hot-order"
mkdir -p "$case_dir"
cat >"$case_dir/lt_newer.md" <<'EOF'
---
name: LT Newer
description: newer triggered
type: feedback
last_triggered: 2026-05-19
trigger_count: 1
created: 2026-04-01
---
EOF
cat >"$case_dir/lt_older.md" <<'EOF'
---
name: LT Older
description: older triggered
type: feedback
last_triggered: 2026-05-05
trigger_count: 1
created: 2026-04-01
---
EOF
cat >"$case_dir/pinned_no_lt.md" <<'EOF'
---
name: Pinned No-LT
description: pinned without last_triggered
type: feedback
pinned: true
pinned_reason: deliberate test fixture
created: 2026-04-01
---
EOF
python3 "$SCRIPT" --emit-index --memory-dir "$case_dir" --today 2026-05-20 >/dev/null
python3 - "$case_dir/MEMORY.md" <<'PY'
import re, sys
text = open(sys.argv[1]).read()
m = re.search(r"## Hot \(\d+\).*?\n\n(.+?)\n\n", text, re.DOTALL)
assert m, "no Hot section: " + text
bullets = [line for line in m.group(1).splitlines() if line.startswith("- ")]
files = [re.search(r"\((.+?)\)", b).group(1) for b in bullets]
assert files == ["lt_newer.md", "lt_older.md", "pinned_no_lt.md"], \
    f"unexpected Hot order: {files}"
PY

echo "PASS: memory-hygiene-emit-index selftest"
