#!/usr/bin/env bash
# post-memory-index-regenerate-hook-selftest.sh — covers MEMORY.md regenerate
# on legal write, skip for non-memory paths, skip for MEMORY.md itself, and
# graceful surface on regenerate failure.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HOOK="$ROOT/.claude/hooks/post-memory-index-regenerate.sh"
TIERING="$ROOT/scripts/memory-hygiene-tiering.py"

[[ -x "$HOOK" ]] || { echo "FAIL: hook missing or not executable: $HOOK" >&2; exit 1; }
[[ -f "$TIERING" ]] || { echo "FAIL: tiering producer missing: $TIERING" >&2; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fail() { echo "FAIL: $*" >&2; exit 1; }

build_json() {
  local tool_name="$1"
  local file_path="$2"
  python3 -c "
import json
print(json.dumps({
  'tool_name': '$tool_name',
  'tool_input': {'file_path': '$file_path'}
}))
"
}

write_member() {
  local mem="$1"
  local name="$2"
  cat > "$mem/$name.md" <<EOF
---
name: $name
description: $name
type: feedback
created: 2026-05-20
last_triggered: 2026-05-20
trigger_count: 1
---

body
EOF
}

# ---------------------------------------------------------------------------
# Test 1: Legal Write → MEMORY.md regenerated with generated marker
# ---------------------------------------------------------------------------
mem="$TMP/t1/memory"
mkdir -p "$mem"
write_member "$mem" "alpha"
# Establish a stale MEMORY.md baseline (no generated markers).
printf "old baseline\n" > "$mem/MEMORY.md"
json=$(build_json "Write" "$mem/alpha.md")
set +e
out="$(printf '%s' "$json" | env CLAUDE_PROJECT_DIR="$ROOT" POLARIS_MEMORY_DIR="$mem" "$HOOK" 2>&1)"
rc=$?
set -e
[[ "$rc" -eq 0 ]] || fail "T1: legal Write should succeed (rc=$rc, out=$out)"
grep -q 'generated by memory-hygiene-tiering.py --emit-index' "$mem/MEMORY.md" \
  || fail "T1: MEMORY.md missing generated marker after regenerate"
grep -q 'end: memory-index generated block' "$mem/MEMORY.md" \
  || fail "T1: MEMORY.md missing end marker after regenerate"
grep -q 'alpha' "$mem/MEMORY.md" || fail "T1: alpha entry not in regenerated index"

# ---------------------------------------------------------------------------
# Test 2: Non-memory path → no regenerate, exit 0
# ---------------------------------------------------------------------------
mkdir -p "$TMP/t2/random"
non="$TMP/t2/random/x.txt"
echo "hi" > "$non"
json=$(build_json "Write" "$non")
set +e
out="$(printf '%s' "$json" | env CLAUDE_PROJECT_DIR="$ROOT" "$HOOK" 2>&1)"
rc=$?
set -e
[[ "$rc" -eq 0 ]] || fail "T2: non-memory path must skip (rc=$rc, out=$out)"

# ---------------------------------------------------------------------------
# Test 3: MEMORY.md PostToolUse → skip (no recursion)
# ---------------------------------------------------------------------------
mem="$TMP/t3/memory"
mkdir -p "$mem"
write_member "$mem" "beta"
# Pre-regenerate so MEMORY.md exists.
POLARIS_MEMORY_HYGIENE_APPLY=1 python3 "$TIERING" --emit-index --memory-dir "$mem" >/dev/null
checksum_before=$(shasum "$mem/MEMORY.md" | awk '{print $1}')
json=$(build_json "Write" "$mem/MEMORY.md")
set +e
out="$(printf '%s' "$json" | env CLAUDE_PROJECT_DIR="$ROOT" POLARIS_MEMORY_DIR="$mem" "$HOOK" 2>&1)"
rc=$?
set -e
[[ "$rc" -eq 0 ]] || fail "T3: MEMORY.md PostToolUse must exit 0 quietly (rc=$rc)"
checksum_after=$(shasum "$mem/MEMORY.md" | awk '{print $1}')
[[ "$checksum_before" == "$checksum_after" ]] || fail "T3: MEMORY.md must not be touched when it IS the written file"

# ---------------------------------------------------------------------------
# Test 4: Edit on memory file → regenerate runs (Hot count diff observable)
# ---------------------------------------------------------------------------
mem="$TMP/t4/memory"
mkdir -p "$mem"
write_member "$mem" "one"
# First regen — baseline.
POLARIS_MEMORY_HYGIENE_APPLY=1 python3 "$TIERING" --emit-index --memory-dir "$mem" >/dev/null
hot_before=$(grep -E '^## Hot' "$mem/MEMORY.md" | head -1)
# Add a second file then fire Edit on it.
write_member "$mem" "two"
json=$(build_json "Edit" "$mem/two.md")
set +e
out="$(printf '%s' "$json" | env CLAUDE_PROJECT_DIR="$ROOT" POLARIS_MEMORY_DIR="$mem" "$HOOK" 2>&1)"
rc=$?
set -e
[[ "$rc" -eq 0 ]] || fail "T4: Edit on memory file should pass (rc=$rc)"
hot_after=$(grep -E '^## Hot' "$mem/MEMORY.md" | head -1)
[[ "$hot_before" != "$hot_after" ]] || fail "T4: Hot count line did not change after second file added"
grep -q 'two' "$mem/MEMORY.md" || fail "T4: regenerated MEMORY.md must mention 'two'"

# ---------------------------------------------------------------------------
# Test 5: MultiEdit on memory file → regenerate fires
# ---------------------------------------------------------------------------
mem="$TMP/t5/memory"
mkdir -p "$mem"
write_member "$mem" "x"
json=$(build_json "MultiEdit" "$mem/x.md")
set +e
out="$(printf '%s' "$json" | env CLAUDE_PROJECT_DIR="$ROOT" POLARIS_MEMORY_DIR="$mem" "$HOOK" 2>&1)"
rc=$?
set -e
[[ "$rc" -eq 0 ]] || fail "T5: MultiEdit should pass (rc=$rc)"
[[ -f "$mem/MEMORY.md" ]] || fail "T5: MEMORY.md must exist after regenerate"
grep -q 'generated by memory-hygiene-tiering.py' "$mem/MEMORY.md" \
  || fail "T5: MEMORY.md missing generated marker after MultiEdit"

# ---------------------------------------------------------------------------
# Test 6: Regenerate failure → exit 1 with structured stderr
# Replace producer script with a stub that exits non-zero.
# ---------------------------------------------------------------------------
mem="$TMP/t6/memory"
mkdir -p "$mem"
write_member "$mem" "z"
stub_script="$TMP/t6/fake-tiering.py"
cat > "$stub_script" <<'EOF'
#!/usr/bin/env python3
import sys
print("simulated regenerate failure", file=sys.stderr)
sys.exit(7)
EOF
chmod +x "$stub_script"
json=$(build_json "Write" "$mem/z.md")
set +e
out="$(printf '%s' "$json" | env CLAUDE_PROJECT_DIR="$ROOT" POLARIS_MEMORY_DIR="$mem" POLARIS_MEMORY_TIERING_SCRIPT="$stub_script" "$HOOK" 2>&1)"
rc=$?
set -e
[[ "$rc" -eq 1 ]] || fail "T6: regenerate failure must surface as exit 1 (rc=$rc, out=$out)"
grep -q 'POLARIS_MEMORY_INDEX_REGENERATE_FAILED' <<< "$out" \
  || fail "T6: regenerate failure must include structured marker"
grep -q 'Recover with:' <<< "$out" || fail "T6: regenerate failure must include recovery hint"

echo "PASS: post-memory-index-regenerate-hook-selftest"
