"""Structured validator authority extracted from scripts/validate-generated-artifact-discipline.sh."""

from __future__ import annotations

import json
from pathlib import Path, PurePosixPath
import re
import shlex
import subprocess
import sys


root = Path(sys.argv[1]).resolve()
base = sys.argv[2]
manifest_path = Path(sys.argv[3])
if not manifest_path.is_absolute():
    manifest_path = root / manifest_path


def block(path: str, reason: str, detail: str = "") -> None:
    suffix = f" detail={detail}" if detail else ""
    print(
        "POLARIS_GENERATED_ARTIFACT_DISCIPLINE_BLOCKED:"
        f"path={path} reason={reason}{suffix}",
        file=sys.stderr,
    )


def safe_repo_relative(raw: object) -> str | None:
    if not isinstance(raw, str) or not raw or raw.startswith("/"):
        return None
    pure = PurePosixPath(raw)
    if ".." in pure.parts:
        return None
    return pure.as_posix()


def head_blob(relative: str) -> bytes | None:
    try:
        return subprocess.check_output(
            ["git", "-C", str(root), "show", f"HEAD:{relative}"],
            stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError:
        return None


def head_file_exists(relative: str | None) -> bool:
    if not relative:
        return False
    return (
        subprocess.run(
            ["git", "-C", str(root), "cat-file", "-e", f"HEAD:{relative}"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        ).returncode
        == 0
    )


if (
    not subprocess.run(
        ["git", "-C", str(root), "rev-parse", "--git-dir"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    ).returncode
    == 0
):
    block("<repo>", "invalid_repository")
    sys.exit(2)

if not base:
    block("<base>", "missing_base_ref")
    sys.exit(2)

try:
    subprocess.run(
        ["git", "-C", str(root), "rev-parse", "--verify", f"{base}^{{commit}}"],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
except subprocess.CalledProcessError:
    block("<base>", "invalid_base_ref", base)
    sys.exit(2)

try:
    raw_added = subprocess.check_output(
        [
            "git",
            "-C",
            str(root),
            "diff",
            "--find-renames",
            "--diff-filter=AR",
            "--name-only",
            "-z",
            f"{base}...HEAD",
        ]
    )
except subprocess.CalledProcessError:
    block("<diff>", "candidate_enumeration_failed", base)
    sys.exit(2)


def is_candidate(relative: str) -> bool:
    pure = PurePosixPath(relative)
    if ".generated" in pure.parts[:-1]:
        return True
    blob = head_blob(relative)
    if blob is None:
        return False
    header_lines = blob.decode("utf-8", errors="replace").splitlines()[:20]
    header_pattern = re.compile(r"^\s*(?:(?:#|>|//|/\*+|\*|<!--)\s*)?Generated by\b")
    return any(header_pattern.search(line) for line in header_lines)


added = [item.decode("utf-8") for item in raw_added.split(b"\0") if item]
candidates = sorted(path for path in added if is_candidate(path))
if not candidates:
    print("PASS: generated-artifact discipline (0 new committed candidates)")
    sys.exit(0)

try:
    manifest_relative = manifest_path.resolve().relative_to(root).as_posix()
except ValueError:
    manifest_relative = ""
manifest_blob = head_blob(manifest_relative) if manifest_relative else None
try:
    if manifest_blob is None:
        raise OSError("manifest is not a committed HEAD blob")
    manifest = json.loads(manifest_blob.decode("utf-8"))
except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
    for candidate in candidates:
        block(candidate, "interface_registry_unreadable", type(exc).__name__)
    sys.exit(2)

rows = manifest.get("generated_artifact_interfaces")
if not isinstance(rows, list):
    for candidate in candidates:
        block(candidate, "interface_registry_missing")
    sys.exit(2)

by_path: dict[str, list[dict[str, object]]] = {}
for row in rows:
    if isinstance(row, dict) and isinstance(row.get("path"), str):
        by_path.setdefault(str(row["path"]), []).append(row)

failed = False
for candidate in candidates:
    matches = by_path.get(candidate, [])
    if not matches:
        block(candidate, "unregistered_interface")
        failed = True
        continue
    if len(matches) != 1:
        block(candidate, "duplicate_interface_registration")
        failed = True
        continue

    row = matches[0]
    required = (
        "classification",
        "generator",
        "freshness_gate",
        "gate_entrypoint",
        "gate_anchor",
    )
    if any(
        not isinstance(row.get(field), str) or not str(row[field]).strip()
        for field in required
    ):
        block(candidate, "interface_registration_incomplete")
        failed = True
        continue
    if row["classification"] != "committed_interface":
        block(candidate, "invalid_interface_classification")
        failed = True
        continue

    generator = safe_repo_relative(row["generator"])
    entrypoint = safe_repo_relative(row["gate_entrypoint"])
    try:
        freshness_tokens = shlex.split(str(row["freshness_gate"]))
    except ValueError:
        freshness_tokens = []
    freshness_bin = (
        safe_repo_relative(freshness_tokens[0]) if freshness_tokens else None
    )

    wired = bool(
        generator
        and head_file_exists(generator)
        and freshness_bin
        and head_file_exists(freshness_bin)
        and entrypoint
        and head_file_exists(entrypoint)
    )
    if wired:
        gate_blob = head_blob(str(entrypoint))
        gate_source = gate_blob.decode("utf-8", errors="replace") if gate_blob else ""
        gate_anchor = str(row["gate_anchor"]).strip()
        executable_lines = [
            line.strip()
            for line in gate_source.splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ]
        wired = gate_anchor in executable_lines
    if not wired:
        block(candidate, "freshness_gate_unwired")
        failed = True

if failed:
    sys.exit(2)

print(
    f"PASS: generated-artifact discipline ({len(candidates)} registered candidate(s))"
)
