#!/usr/bin/env bash
set -euo pipefail

# compile-runtime-instructions.sh
#
# Source of truth: .claude/instructions/manifest.yaml
# Generated targets:
#   - CLAUDE.md
#   - AGENTS.md
#   - .codex/AGENTS.md
#   - .github/copilot-instructions.md
#   - runtime instruction manifest files under .generated directories
#
# Usage:
#   bash scripts/compile-runtime-instructions.sh
#   bash scripts/compile-runtime-instructions.sh --target {claude|agents|codex|copilot|all}
#   bash scripts/compile-runtime-instructions.sh --check

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

MANIFEST="$ROOT_DIR/.claude/instructions/manifest.yaml"
CHECK_ONLY=false
TARGET="all"

usage() {
  sed -n '1,20p' "$0" >&2
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      CHECK_ONLY=true
      shift
      ;;
    --target)
      [[ $# -ge 2 ]] || usage
      TARGET="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      ;;
  esac
done

case "$TARGET" in
  claude|agents|codex|copilot|all) ;;
  *) echo "Invalid target: $TARGET" >&2; exit 2 ;;
esac

[[ -f "$MANIFEST" ]] || {
  echo "Missing manifest: $MANIFEST" >&2
  exit 1
}

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

list_universal_rules() {
  find "$ROOT_DIR/.claude/rules" -maxdepth 1 -type f -name '*.md' | sort | sed "s#^$ROOT_DIR/##"
}

write_manifest_snapshot() {
  local out="$1"
  {
    echo "source_of_truth=.claude/instructions/manifest.yaml"
    echo "generated_at=deterministic"
    echo
    echo "[sources]"
    printf '%s\n' ".claude/instructions/core/bootstrap.md"
    printf '%s\n' ".claude/instructions/runtime/claude.md"
    printf '%s\n' ".claude/instructions/runtime/codex.md"
    printf '%s\n' ".claude/instructions/runtime/copilot.md"
    list_universal_rules
    echo
    echo "[sha256]"
    while IFS= read -r rel; do
      [[ -f "$ROOT_DIR/$rel" ]] || continue
      sha="$(shasum -a 256 "$ROOT_DIR/$rel" | awk '{print $1}')"
      printf '%s  %s\n' "$sha" "$rel"
    done < <({
      printf '%s\n' ".claude/instructions/manifest.yaml"
      printf '%s\n' ".claude/instructions/core/bootstrap.md"
      printf '%s\n' ".claude/instructions/runtime/claude.md"
      printf '%s\n' ".claude/instructions/runtime/codex.md"
      printf '%s\n' ".claude/instructions/runtime/copilot.md"
      list_universal_rules
    } | sort -u)
  } > "$out"
}

emit_header() {
  local title="$1"
  local target_name="$2"
  cat <<EOF
# $title

> Generated by \`scripts/compile-runtime-instructions.sh\`.
> source of truth: \`.claude/instructions/manifest.yaml\`.
> manual edit policy: do not edit generated target content directly; update \`.claude/instructions/**\`, \`.claude/rules/**\`, or the compiler.
> regenerate: \`bash scripts/compile-runtime-instructions.sh --target $target_name\`.
> check: \`bash scripts/compile-runtime-instructions.sh --target $target_name --check\`.

EOF
}

emit_core() {
  cat <<'EOF'
## What Polaris Is

Polaris is a workspace-owned AI engineering harness. It routes user intent to skills, keeps planning and execution artifacts explicit, and moves repeatable behavior into deterministic scripts and hooks instead of relying on LLM memory.

The framework is an add-on layer. Product repositories keep ownership of their tracked `CLAUDE.md`, `AGENTS.md`, `.github/**`, and tracked `.claude/**` files unless a repo owner explicitly opts in to a tracked adapter.

## Operating Model

1. Read the user's intent and route to the matching skill before improvising.
2. For code changes, find the authoritative `task.md`; framework work uses DP-backed tasks under `docs-manager/src/content/docs/specs/design-plans/DP-*/tasks/`.
3. Load relevant references from `.claude/skills/references/INDEX.md`.
4. Run deterministic gates instead of relying on memory.
5. Keep company/project config under ignored local `{company}/polaris-config/`; this is the only steady-state runtime lookup path.

## Ownership Boundaries

| Layer | Ownership | Examples |
|-------|-----------|----------|
| Polaris workspace/template | Polaris-owned | generated runtime targets, `.claude/instructions/**`, `.claude/rules/**`, `.claude/skills/**`, scripts, hooks |
| Company config in workspace | Polaris-owned local ignored config | `{company}/polaris-config/**` |
| Product repo tracked files | repo-owned | repo `CLAUDE.md`, `AGENTS.md`, `.github/**`, tracked `.claude/**` |
| Product repo local overlay | Polaris local ignored fallback | ignored files with explicit reason code |

## Where To Load Details

- Routing and behavioral rules: `.claude/rules/*.md`
- Skill procedures: `.claude/skills/*/SKILL.md`
- Shared skill references: `.claude/skills/references/INDEX.md`
- Runtime instruction graph: `.claude/instructions/manifest.yaml`
- Company/project handbook SoT: `{company}/polaris-config/{project}/handbook/`

EOF
}

emit_rule_index() {
  echo "## Universal Rule Index"
  echo
  echo "Global targets reference universal rules without inlining their full bodies. Load the relevant files explicitly when the task context requires them."
  echo
  while IFS= read -r rel; do
    printf -- '- `%s`\n' "$rel"
  done < <(list_universal_rules)
}

emit_communication() {
  cat <<'EOF'
## Communication

Use the workspace language from `workspace-config.yaml` as the default authoring language when present. Draft user-facing and downstream-facing prose directly in that language; do not rely on writing English first and translating immediately before sending.

Keep user updates concise, factual, and tied to the current gate or blocker.
EOF
}

emit_claude() {
  emit_header "Polaris Framework Bootstrap" "claude"
  emit_core
  cat <<'EOF'
## Claude Runtime Notes

Claude Code sees this file as first context. Keep this bootstrap thin: framework identity, routing posture, deterministic enforcement, and source locations only.

## Deterministic Enforcement

When behavioral drift appears, prefer scripts, hooks, validators, or skill checkpoints over new prose reminders. If a mandatory gate fails, stop and fix the underlying contract.
EOF
  echo
  emit_communication
}

emit_agents() {
  emit_header "AGENTS" "agents"
  emit_core
  cat <<'EOF'
## Agent Runtime Notes

This is a Polaris-owned bootstrap for coding agents. It does not imply installation into product repo roots. Host repo `AGENTS.md` files are repo-owned.
EOF
  echo
  emit_communication
  echo
  emit_rule_index
}

emit_codex() {
  emit_header "AGENTS" "codex"
  emit_core
  cat <<'EOF'
## Codex Runtime Notes

Codex-compatible entrypoints use AGENTS conventions. This `.codex/AGENTS.md` file is a local compatibility target for the Polaris workspace; product repo root `AGENTS.md` files remain repo-owned.
EOF
  echo
  emit_communication
  echo
  emit_rule_index
}

emit_copilot() {
  emit_header "Copilot Instructions - Polaris Workspace" "copilot"
  emit_core
  cat <<'EOF'
## Copilot Runtime Notes

Copilot-compatible instructions are generated for the Polaris workspace/template only. Product repo `.github/**` files are repo-owned and are not patched by default.

Copilot does not provide Claude Code's hook model. Before git or GitHub actions, run the deterministic scripts named by the active task and by the relevant skill reference.
EOF
  echo
  emit_communication
  echo
  emit_rule_index
}

write_target() {
  local name="$1"
  local path="$2"
  local render="$3"
  local tmp="$tmpdir/$name.out"
  local manifest_tmp="$tmpdir/$name.manifest"

  "$render" > "$tmp"
  write_manifest_snapshot "$manifest_tmp"

  if [[ "$CHECK_ONLY" == true ]]; then
    [[ -f "$path" ]] || { echo "DRIFT: missing $path" >&2; return 1; }
    if ! diff -q "$tmp" "$path" >/dev/null 2>&1; then
      echo "DRIFT: $path is out of date." >&2
      diff -u "$path" "$tmp" | head -80 >&2
      return 1
    fi
    return 0
  fi

  mkdir -p "$(dirname "$path")"
  cp "$tmp" "$path"
  echo "Generated: $path"
}

write_generated_manifest_targets() {
  local manifest_tmp="$tmpdir/runtime-instructions-manifest.txt"
  write_manifest_snapshot "$manifest_tmp"

  local targets=(
    "$ROOT_DIR/.codex/.generated/rules-manifest.txt"
    "$ROOT_DIR/.github/.generated/copilot-rules-manifest.txt"
  )
  for path in "${targets[@]}"; do
    if [[ "$CHECK_ONLY" == true ]]; then
      [[ -f "$path" ]] || { echo "DRIFT: missing $path" >&2; return 1; }
      diff -q "$manifest_tmp" "$path" >/dev/null 2>&1 || { echo "DRIFT: $path is out of date." >&2; return 1; }
    else
      mkdir -p "$(dirname "$path")"
      cp "$manifest_tmp" "$path"
      echo "Generated: $path"
    fi
  done
}

run_target() {
  local t="$1"
  case "$t" in
    claude) write_target claude "$ROOT_DIR/CLAUDE.md" emit_claude ;;
    agents) write_target agents "$ROOT_DIR/AGENTS.md" emit_agents ;;
    codex) write_target codex "$ROOT_DIR/.codex/AGENTS.md" emit_codex ;;
    copilot) write_target copilot "$ROOT_DIR/.github/copilot-instructions.md" emit_copilot ;;
  esac
}

if [[ "$TARGET" == "all" ]]; then
  run_target claude
  run_target agents
  run_target codex
  run_target copilot
  write_generated_manifest_targets
else
  run_target "$TARGET"
  write_generated_manifest_targets
fi

if [[ "$CHECK_ONLY" == true ]]; then
  echo "OK: runtime instruction targets are in sync."
fi
