#!/usr/bin/env bash
set -euo pipefail

# compile-runtime-instructions.sh
#
# Source of truth: .claude/instructions/manifest.yaml
# Generated targets:
#   - CLAUDE.md
#   - AGENTS.md
#   - .codex/AGENTS.md
#   - .github/copilot-instructions.md
#   - runtime instruction manifest files under .generated directories
#
# Usage:
#   bash scripts/compile-runtime-instructions.sh
#   bash scripts/compile-runtime-instructions.sh --target {claude|agents|codex|copilot|all}
#   bash scripts/compile-runtime-instructions.sh --check

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

MANIFEST="$ROOT_DIR/.claude/instructions/manifest.yaml"
CHECK_ONLY=false
TARGET="all"

usage() {
  sed -n '1,20p' "$0" >&2
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      CHECK_ONLY=true
      shift
      ;;
    --target)
      [[ $# -ge 2 ]] || usage
      TARGET="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      ;;
  esac
done

case "$TARGET" in
  claude|agents|codex|copilot|all) ;;
  *) echo "Invalid target: $TARGET" >&2; exit 2 ;;
esac

[[ -f "$MANIFEST" ]] || {
  echo "Missing manifest: $MANIFEST" >&2
  exit 1
}

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

list_universal_rules() {
  find "$ROOT_DIR/.claude/rules" -maxdepth 1 -type f -name '*.md' | sort | sed "s#^$ROOT_DIR/##"
}

write_manifest_snapshot() {
  local out="$1"
  local sources_file="$tmpdir/sources.list"
  : > "$sources_file"
  printf '%s\n' ".claude/instructions/manifest.yaml" >> "$sources_file"
  printf '%s\n' ".claude/instructions/core/bootstrap.md" >> "$sources_file"
  printf '%s\n' ".claude/instructions/runtime/claude.md" >> "$sources_file"
  printf '%s\n' ".claude/instructions/runtime/codex.md" >> "$sources_file"
  printf '%s\n' ".claude/instructions/runtime/copilot.md" >> "$sources_file"
  list_universal_rules >> "$sources_file"

  echo "source_of_truth=.claude/instructions/manifest.yaml" > "$out"
  echo "generated_at=deterministic" >> "$out"
  echo >> "$out"
  echo "[sources]" >> "$out"
  grep -v '^.claude/instructions/manifest.yaml$' "$sources_file" | sort -u >> "$out"
  echo >> "$out"
  echo "[sha256]" >> "$out"
  sort -u "$sources_file" | while read -r rel; do
    [[ -f "$ROOT_DIR/$rel" ]] || continue
    sha="$(shasum -a 256 "$ROOT_DIR/$rel" | awk '{print $1}')"
    printf '%s  %s\n' "$sha" "$rel" >> "$out"
  done
}

emit_header() {
  local title="$1"
  local target_name="$2"
  cat <<EOF
# $title

> Generated by \`scripts/compile-runtime-instructions.sh\`.
> source of truth: \`.claude/instructions/manifest.yaml\`.
> manual edit policy: do not edit generated target content directly; update \`.claude/instructions/**\`, \`.claude/rules/**\`, or the compiler.
> regenerate: \`bash scripts/compile-runtime-instructions.sh --target $target_name\`.
> check: \`bash scripts/compile-runtime-instructions.sh --target $target_name --check\`.

EOF
}

emit_core() {
  cat <<'EOF'
## What Polaris Is

Polaris is a workspace-owned AI engineering harness. It routes user intent to skills, keeps planning and execution artifacts explicit, and moves repeatable behavior into deterministic scripts and hooks instead of relying on LLM memory.

The framework is an add-on layer. Product repositories keep ownership of their tracked `CLAUDE.md`, `AGENTS.md`, `.github/**`, and tracked `.claude/**` files unless a repo owner explicitly opts in to a tracked adapter.

## Operating Model

1. Read the user's intent and route to the matching skill before improvising.
2. For code changes, find the authoritative `task.md`; framework work uses DP-backed tasks under `docs-manager/src/content/docs/specs/design-plans/DP-*/tasks/`.
3. Load relevant references from `.claude/skills/references/INDEX.md`.
4. Run deterministic gates instead of relying on memory.
5. Keep company/project config under ignored local `{company}/polaris-config/`; this is the only steady-state runtime lookup path.

## Ownership Boundaries

| Layer | Ownership | Examples |
|-------|-----------|----------|
| Polaris workspace/template | Polaris-owned | generated runtime targets, `.claude/instructions/**`, `.claude/rules/**`, `.claude/skills/**`, scripts, hooks |
| Company config in workspace | Polaris-owned local ignored config | `{company}/polaris-config/**` |
| Product repo tracked files | repo-owned | repo `CLAUDE.md`, `AGENTS.md`, `.github/**`, tracked `.claude/**` |
| Product repo local overlay | Polaris local ignored fallback | ignored files with explicit reason code |

## Where To Load Details

- Routing and behavioral rules: `.claude/rules/*.md`
- Skill procedures: `.claude/skills/*/SKILL.md`
- Shared skill references: `.claude/skills/references/INDEX.md`
- Runtime instruction graph: `.claude/instructions/manifest.yaml`
- Company/project handbook SoT: `{company}/polaris-config/{project}/handbook/`

## Full Source Completion Invariant

When the user asks to complete a DP, source, Epic, or full workflow, completion is source-level, not task-local. A single task, blocker hotfix, PR, version tag, framework-release closeout, or local-extension deliverable is not completion while sibling tasks, V tasks, verification disposition, source status, or parent lifecycle closeout remain incomplete.

Agents must report the partial state and continue or reroute the owning workflow. They must not declare the source complete, stop at a task-local release, or replace the requested full workflow with a narrower blocker fix unless the user explicitly changes scope.

EOF
}

emit_decision_priority_principle() {
  cat <<'EOF'
## Decision Priority Principle

所有 agent 行為（包含 strategist orchestration 與 sub-agent 內部判斷）依下列三原則決策，重要性遞減：

1. **功能完整**：交付物必須真正解決所述問題，不得以裁掉必要功能換取其他屬性。
2. **易讀**：產出（程式碼、文件、報告）必須讓接手者能直接理解，不得以晦澀換取其他屬性。
3. **效能/簡潔**：相同前提下偏好更短、更快、更少抽象的方案。

Trade-off 規則：

- 三項衝突時從尾項開始放棄（先放效能/簡潔，再放易讀），第 1 項絕不放棄。
- 不得反向：絕不為了效能或簡潔犧牲功能完整或易讀。

選項判斷規則：

- 當出現候選方案時，優先依本原則直接決定並交付一個方案，附 reasoning 與 tradeoff。
- 不得把當前 skill 契約已排除的選項（forbidden_actions、consent_excludes、dispatch_boundary 之外的動作）列給使用者選，也不得寫進 self-authored report 的 `manual_items[]`、handoff prompt 或下一 session 的選項清單。違反契約的選項在 writer 端就要過濾，不應留待 reader 端再檢查。
EOF
}

emit_rule_index() {
  echo "## Universal Rule Index"
  echo
  echo "Global targets reference universal rules without inlining their full bodies. Load the relevant files explicitly when the task context requires them."
  echo
  while read -r rel; do
    printf -- '- `%s`\n' "$rel"
  done < <(list_universal_rules)
}

emit_communication() {
  cat <<'EOF'
## Communication

Use the workspace language from `workspace-config.yaml` as the default authoring language when present. Draft user-facing and downstream-facing prose directly in that language; do not rely on writing English first and translating immediately before sending. If a skill will produce an artifact, preview, handoff, or external write body, load `.claude/skills/references/authoring-preflight.md` and `.claude/skills/references/workspace-language-policy.md` before drafting.

Keep user updates concise, factual, and tied to the current gate or blocker.
EOF
}

emit_plugin_workflow_quarantine() {
  cat <<'EOF'
## Plugin Workflow Quarantine

Plugin workflow authority lives in `.claude/skills/references/plugin-workflow-quarantine.md`;
load it with `.claude/rules/skill-routing.md` whenever plugin workflows and Polaris-managed delivery could both match.
EOF
}

emit_final_response_language_guard_core() {
  cat <<'EOF'
## Final Response Language Guard

The agent's final/chat response delivered back to the user — including reports, summaries, status updates, and any natural-language reply that is not an internal tool call — is **user-facing prose** under the same `workspace-config.yaml` `language` contract that governs artifacts, PR bodies, JIRA comments, and Slack messages.

- File-write hooks (`pre-write-language-policy.sh`) and external-write preflights only catch writes to files or external surfaces; they do **not** intercept the final/chat response stream.
- The agent must self-check the workspace language **before** emitting any final response. If `workspace-config.yaml` declares `language: zh-TW`, the final response prose must be Traditional Chinese; identifiers (function names, file paths, ticket keys, command strings) remain in their original form.
- The language guard is not an opt-in; missing `language` falls back to English advisory drafts, but a declared workspace language is mandatory for all final responses.
EOF
}

emit_final_response_language_guard_claude() {
  cat <<'EOF'
### Claude Code Runtime Caveat

Claude Code's PreToolUse / PostToolUse hooks fire on tool calls, not on the assistant's final message. `pre-write-language-policy.sh` does not run when the model emits a chat response without invoking a Write/Edit tool. The agent must self-check `workspace-config.yaml` `language` before sending any final response, including engineering reports, verify-AC summaries, refinement updates, and skill output. Do not draft the reply in another language and translate at the end; author in the workspace language from the first sentence.
EOF
}

emit_final_response_language_guard_codex() {
  cat <<'EOF'
### Codex Runtime Caveat

Codex runtimes have no Claude Code hook model. Neither `pre-write-language-policy.sh` nor any PreToolUse interception fires on Codex final/chat responses. The agent must self-check `workspace-config.yaml` `language` before emitting any final response. Authoring discipline is the only enforcement layer for the final reply; do not assume a downstream validator will catch a wrong-language summary.
EOF
}

emit_final_response_language_guard_copilot() {
  cat <<'EOF'
### Copilot Runtime Caveat

Copilot has no PreToolUse hook and no Polaris-side interception of the final/chat response. The agent must self-check `workspace-config.yaml` `language` before sending any final reply. The compile-time language gate only covers files and external writes; the natural-language response stream is governed solely by the agent's own authoring discipline.
EOF
}

emit_root_toolchain_runtime_note() {
  cat <<'EOF'
For a fresh Polaris workspace, initialize root runtime dependencies before company onboarding:

```bash
mise run bootstrap
mise run doctor -- --profile runtime
```

Then run the agent-facing `onboard` workflow. Public tasks are `bootstrap`, `doctor`, `doctor-mise`, `onboard-doctor`, `release-preflight`, `pr-create`, `spec-close-parent`, `script-audit`, `docs-health`, `verify`, and `cross-runtime-sync`. Root `pnpm` commands are thin aliases only; they are not the Polaris root runtime manager.
EOF
}

emit_claude() {
  emit_header "Polaris Framework Bootstrap" "claude"
  emit_core
  emit_decision_priority_principle
  echo
  cat <<'EOF'
## Claude Runtime Notes

Claude Code sees this file as first context. Keep this bootstrap thin: framework identity, routing posture, deterministic enforcement, and source locations only.

## Deterministic Enforcement

When behavioral drift appears, prefer scripts, hooks, validators, or skill checkpoints over new prose reminders. If a mandatory gate fails, stop and fix the underlying contract.
EOF
  echo
  emit_communication
  echo
  emit_final_response_language_guard_core
  echo
  emit_final_response_language_guard_claude
  echo
  emit_plugin_workflow_quarantine
}

emit_agents() {
  emit_header "AGENTS" "agents"
  emit_core
  emit_decision_priority_principle
  echo
  cat <<'EOF'
## Agent Runtime Notes

This is a Polaris-owned bootstrap for coding agents. It does not imply installation into product repo roots. Host repo `AGENTS.md` files are repo-owned.
EOF
  echo
  emit_root_toolchain_runtime_note
  echo
  emit_communication
  echo
  emit_final_response_language_guard_core
  echo
  emit_final_response_language_guard_codex
  echo
  emit_plugin_workflow_quarantine
  echo
  emit_rule_index
}

emit_codex() {
  emit_header "AGENTS" "codex"
  emit_core
  emit_decision_priority_principle
  echo
  cat <<'EOF'
## Codex Runtime Notes

Codex-compatible entrypoints use AGENTS conventions. This `.codex/AGENTS.md` file is a local compatibility target for the Polaris workspace; product repo root `AGENTS.md` files remain repo-owned.
EOF
  echo
  emit_root_toolchain_runtime_note
  echo
  emit_communication
  echo
  emit_final_response_language_guard_core
  echo
  emit_final_response_language_guard_codex
  echo
  emit_plugin_workflow_quarantine
  echo
  emit_rule_index
}

emit_copilot() {
  emit_header "Copilot Instructions - Polaris Workspace" "copilot"
  emit_core
  emit_decision_priority_principle
  echo
  cat <<'EOF'
## Copilot Runtime Notes

Copilot-compatible instructions are generated for the Polaris workspace/template only. Product repo `.github/**` files are repo-owned and are not patched by default.

Copilot does not provide Claude Code's hook model. Before git or GitHub actions, run the deterministic scripts named by the active task and by the relevant skill reference.
EOF
  echo
  emit_communication
  echo
  emit_final_response_language_guard_core
  echo
  emit_final_response_language_guard_copilot
  echo
  emit_rule_index
}

write_target() {
  local name="$1"
  local path="$2"
  local render="$3"
  local tmp="$tmpdir/$name.out"
  local manifest_tmp="$tmpdir/$name.manifest"

  "$render" > "$tmp"
  write_manifest_snapshot "$manifest_tmp"

  if [[ "$CHECK_ONLY" == true ]]; then
    [[ -f "$path" ]] || { echo "DRIFT: missing $path" >&2; return 1; }
    if ! command diff -q "$tmp" "$path" >/dev/null 2>&1; then
      echo "DRIFT: $path is out of date." >&2
      command diff -u "$path" "$tmp" | head -80 >&2
      return 1
    fi
    return 0
  fi

  mkdir -p "$(dirname "$path")"
  cp "$tmp" "$path"
  echo "Generated: $path"
}

write_generated_manifest_targets() {
  local manifest_tmp="$tmpdir/runtime-instructions-manifest.txt"
  write_manifest_snapshot "$manifest_tmp"

  local targets=(
    "$ROOT_DIR/.codex/.generated/rules-manifest.txt"
    "$ROOT_DIR/.github/.generated/copilot-rules-manifest.txt"
  )
  for path in "${targets[@]}"; do
    if [[ "$CHECK_ONLY" == true ]]; then
      [[ -f "$path" ]] || { echo "DRIFT: missing $path" >&2; return 1; }
      command diff -q "$manifest_tmp" "$path" >/dev/null 2>&1 || { echo "DRIFT: $path is out of date." >&2; return 1; }
    else
      mkdir -p "$(dirname "$path")"
      cp "$manifest_tmp" "$path"
      echo "Generated: $path"
    fi
  done
}

run_target() {
  local t="$1"
  case "$t" in
    claude) write_target claude "$ROOT_DIR/CLAUDE.md" emit_claude ;;
    agents) write_target agents "$ROOT_DIR/AGENTS.md" emit_agents ;;
    codex) write_target codex "$ROOT_DIR/.codex/AGENTS.md" emit_codex ;;
    copilot) write_target copilot "$ROOT_DIR/.github/copilot-instructions.md" emit_copilot ;;
  esac
}

if [[ "$TARGET" == "all" ]]; then
  run_target claude
  run_target agents
  run_target codex
  run_target copilot
  write_generated_manifest_targets
else
  run_target "$TARGET"
  write_generated_manifest_targets
fi

if [[ "$CHECK_ONLY" == true ]]; then
  echo "OK: runtime instruction targets are in sync."
fi
