#!/usr/bin/env bash
# Sync workspace specs/ into the Starlight docs-viewer content tree.
# Usage: generate-specs-sidebar.sh [workspace_root]
#
# Historical name retained for hook compatibility. The Starlight viewer uses
# autogenerated sidebar groups from docs-viewer/src/content/docs/specs/.

set -euo pipefail

WORKSPACE_ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
SPECS_ROOT="$WORKSPACE_ROOT/specs"
VIEWER_DOCS_DIR="$WORKSPACE_ROOT/docs-viewer/src/content/docs"
TARGET_SPECS_DIR="$VIEWER_DOCS_DIR/specs"

mkdir -p "$VIEWER_DOCS_DIR"

if [[ ! -d "$SPECS_ROOT" ]]; then
  rm -rf "$TARGET_SPECS_DIR"
  echo "Synced: no specs directory found"
  exit 0
fi

python3 - "$WORKSPACE_ROOT" "$SPECS_ROOT" "$TARGET_SPECS_DIR" <<'PY'
import re
import shutil
import sys
from pathlib import Path

workspace_root = Path(sys.argv[1]).resolve()
specs_root = Path(sys.argv[2]).resolve()
target_root = Path(sys.argv[3]).resolve()

if target_root.exists():
    shutil.rmtree(target_root)
target_root.mkdir(parents=True, exist_ok=True)

SKIP_DIRS = {".git", ".worktrees", "node_modules"}


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        return {}, text
    lines = text.splitlines()
    for idx in range(1, len(lines)):
        if lines[idx] == "---":
            fm_lines = lines[1:idx]
            body = "\n".join(lines[idx + 1 :])
            if text.endswith("\n"):
                body += "\n"
            data: dict[str, str] = {}
            for line in fm_lines:
                if ":" not in line or line.startswith((" ", "\t")):
                    continue
                key, value = line.split(":", 1)
                data[key.strip()] = value.strip().strip('"').strip("'")
            return data, body
    return {}, text


def first_heading(text: str) -> str | None:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


def status_badge(status: str | None) -> str:
    return {
        "SEEDED": " 🌱",
        "DISCUSSION": " 💬",
        "LOCKED": " 🔒",
        "IMPLEMENTED": " ✅",
        "ABANDONED": " ❌",
    }.get(status or "", "")


def title_for(path: Path, metadata: dict[str, str], body: str) -> str:
    title = metadata.get("title") or metadata.get("topic") or first_heading(body)
    if not title:
        title = path.stem
    return re.sub(r"\s+", " ", title).strip() + status_badge(metadata.get("status"))


def yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def task_label(title: str) -> str:
    match = re.match(r"^(T\d+[a-z]*):\s*(.+?)\s*\([0-9.]+\s*pt\)\s*$", title, re.IGNORECASE)
    if match:
        return f"{match.group(1)}: {match.group(2)}"
    return title


def title_case_slug(value: str) -> str:
    return re.sub(r"\s+", " ", value.replace("-", " ").replace("_", " ")).strip().title()


def sidebar_label_for(rel: Path, title: str) -> str:
    name = rel.name.lower()
    parts = [part.lower() for part in rel.parts]
    if name == "plan.md":
        return "Plan"
    if name == "refinement.md":
        return "Refinement"
    if name == "breakdown.md":
        return "Breakdown"
    if "tasks" in parts:
        return task_label(title)
    if "artifacts" in parts:
        return title_case_slug(rel.stem)
    if "escalations" in parts:
        return rel.stem.upper()
    if "verification" in parts or "refinement-inbox" in parts:
        return title_case_slug(rel.stem)
    return title


def task_order(stem: str) -> int:
    match = re.match(r"t(\d+)([a-z]*)$", stem.lower())
    if not match:
        return 199
    suffix = match.group(2)
    suffix_weight = 0
    if suffix:
        suffix_weight = ord(suffix[0]) - ord("a") + 1
    return 100 + int(match.group(1)) * 10 + suffix_weight


def sidebar_order_for(rel: Path) -> int:
    name = rel.name.lower()
    parts = [part.lower() for part in rel.parts]
    if name == "plan.md":
        return 0
    if name == "refinement.md":
        return 10
    if name == "breakdown.md":
        return 20
    if "tasks" in parts:
        return task_order(rel.stem)
    if "artifacts" in parts:
        return 300
    if "escalations" in parts:
        return 400
    if "refinement-inbox" in parts:
        return 500
    if "verification" in parts:
        return 600
    return 200


def hide_from_sidebar(rel: Path) -> bool:
    parts = {part.lower() for part in rel.parts}
    return bool({"verification", "refinement-inbox"} & parts)


def exclude_from_search(rel: Path) -> bool:
    parts = {part.lower() for part in rel.parts}
    return bool({"verification", "refinement-inbox"} & parts)


def normalize_heading(value: str) -> str:
    value = re.sub(r"[🌱💬🔒✅❌]", "", value)
    value = value.replace("：", ":")
    value = re.sub(r"[^a-z0-9]+", " ", value.lower())
    value = re.sub(r"\s+", " ", value).strip()
    return re.sub(r"^dp \d+ ", "", value)


def remove_duplicate_h1(body: str, title: str) -> str:
    lines = body.splitlines(keepends=True)
    for idx, line in enumerate(lines):
        if not line.startswith("# "):
            if line.strip():
                return body
            continue
        heading = line[2:].strip()
        if normalize_heading(heading) == normalize_heading(title):
            return "".join(lines[:idx] + lines[idx + 1 :]).lstrip()
        return body
    return body


count = 0
for source in sorted(specs_root.rglob("*.md")):
    if any(part in SKIP_DIRS for part in source.relative_to(specs_root).parts):
        continue
    rel = source.relative_to(specs_root)
    dest = target_root / rel
    dest.parent.mkdir(parents=True, exist_ok=True)

    raw = source.read_text(encoding="utf-8")
    metadata, body = split_frontmatter(raw)
    title = title_for(source, metadata, body)
    body = remove_duplicate_h1(body, title)
    source_path = source.relative_to(workspace_root)
    sidebar_label = sidebar_label_for(rel, title)
    sidebar_order = sidebar_order_for(rel)

    frontmatter = [
        "---",
        f"title: {yaml_quote(title)}",
        f"description: {yaml_quote(str(source_path))}",
        "sidebar:",
        f"  label: {yaml_quote(sidebar_label)}",
        f"  order: {sidebar_order}",
    ]
    if hide_from_sidebar(rel):
        frontmatter.append("  hidden: true")
    if exclude_from_search(rel):
        frontmatter.append("pagefind: false")
    frontmatter.append("---")

    generated = "\n".join(frontmatter) + "\n\n" + f"> Source: `{source_path}`\n\n" + body.lstrip()
    dest.write_text(generated, encoding="utf-8")
    count += 1

print(f"Synced: {count} markdown files to {target_root}")
PY
