#!/usr/bin/env bash
# Generate _sidebar.md for docsify specs viewer
# Usage: generate-specs-sidebar.sh [workspace_root]
#
# Scans specs/design-plans/ and {company}/specs/ to build a navigation sidebar.
# Output: docs-viewer/_sidebar.md (paths relative to workspace root for basePath: '/')

set -euo pipefail

WORKSPACE_ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
VIEWER_DIR="$WORKSPACE_ROOT/docs-viewer"
SIDEBAR="$VIEWER_DIR/_sidebar.md"

mkdir -p "$VIEWER_DIR"

# --- Helpers ---

extract_frontmatter_field() {
  local file="$1" field="$2"
  sed -n '/^---$/,/^---$/p' "$file" 2>/dev/null \
    | grep "^${field}:" \
    | head -1 \
    | sed "s/^${field}:[[:space:]]*//"
}

extract_title() {
  local file="$1"
  local topic
  topic=$(extract_frontmatter_field "$file" "topic")
  if [ -n "$topic" ]; then
    echo "$topic"
    return
  fi
  grep -m1 '^# ' "$file" 2>/dev/null | sed 's/^# //' || basename "$(dirname "$file")"
}

status_badge() {
  local file="$1"
  local status
  status=$(extract_frontmatter_field "$file" "status")
  case "$status" in
    DISCUSSION)   echo " 💬" ;;
    LOCKED)       echo " 🔒" ;;
    IMPLEMENTED)  echo " ✅" ;;
    ABANDONED)    echo " ❌" ;;
    *)            echo "" ;;
  esac
}

# --- Build sidebar ---

{
  echo "<!-- Auto-generated by generate-specs-sidebar.sh -->"
  echo ""
  echo "* [Home](docs-viewer/home.md)"
  echo ""

  # Section: Design Plans
  echo "* **Design Plans**"
  for dp_dir in "$WORKSPACE_ROOT"/specs/design-plans/DP-*/; do
    [ -d "$dp_dir" ] || continue
    plan_file="$dp_dir/plan.md"
    [ -f "$plan_file" ] || continue

    dp_name=$(basename "$dp_dir")
    dp_num=$(echo "$dp_name" | grep -o 'DP-[0-9]*')
    title=$(extract_title "$plan_file")
    badge=$(status_badge "$plan_file")

    status=$(extract_frontmatter_field "$plan_file" "status")
    if [ "$status" = "IMPLEMENTED" ] || [ "$status" = "ABANDONED" ]; then
      echo "  * <span class=\"done\">[$dp_num: $title$badge](specs/design-plans/$dp_name/plan.md)</span>"
    else
      echo "  * [$dp_num: $title$badge](specs/design-plans/$dp_name/plan.md)"
    fi
  done

  echo ""

  # Section: Epic Specs (scan all company dirs)
  for company_dir in "$WORKSPACE_ROOT"/*/; do
    company=$(basename "$company_dir")
    specs_dir="$company_dir/specs"
    [ -d "$specs_dir" ] || continue

    # Skip non-company dirs
    epic_count=$(find "$specs_dir" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
    [ "$epic_count" -gt 0 ] || continue

    echo "* **$company — Specs**"

    for epic_dir in "$specs_dir"/*/; do
      [ -d "$epic_dir" ] || continue
      epic=$(basename "$epic_dir")

      # Skip empty epics (no refinement, no tasks, no plan)
      has_refinement=false
      has_tasks=false
      has_plan=false
      [ -f "$epic_dir/refinement.md" ] && has_refinement=true
      [ -d "$epic_dir/tasks" ] && [ -n "$(ls "$epic_dir/tasks/"*.md 2>/dev/null)" ] && has_tasks=true
      [ -f "$epic_dir/plan.md" ] && has_plan=true
      if ! $has_refinement && ! $has_tasks && ! $has_plan; then
        continue
      fi

      # Detect issue type badge: refinement.json "type" > plan.md "> Type:" > default (Epic)
      type_badge="📦"  # default: Epic
      if [ -f "$epic_dir/refinement.json" ]; then
        json_type=$(python3 -c "import json,sys; print(json.load(open('$epic_dir/refinement.json')).get('type',''))" 2>/dev/null || true)
        case "$json_type" in
          bug|Bug)   type_badge="🐛" ;;
          task|Task) type_badge="📋" ;;
        esac
      elif [ -f "$epic_dir/plan.md" ]; then
        plan_type=$(grep -m1 '^> Type:' "$epic_dir/plan.md" 2>/dev/null | sed 's/^> Type:[[:space:]]*//' || true)
        case "$plan_type" in
          Bug|bug)   type_badge="🐛" ;;
          Task|task) type_badge="📋" ;;
        esac
      fi

      # Ticket header (badge inside link text to prevent line break)
      if [ -f "$epic_dir/refinement.md" ]; then
        echo "  * [$type_badge $epic — Refinement]($company/specs/$epic/refinement.md)"
      elif [ -f "$epic_dir/plan.md" ]; then
        plan_title=$(grep -m1 '^# ' "$epic_dir/plan.md" 2>/dev/null | sed 's/^# //' || echo "$epic")
        # Strip leading ticket key from title to avoid "KEY — KEY — title" duplication
        plan_title=$(echo "$plan_title" | sed "s/^${epic}[[:space:]]*[—–-][[:space:]]*//")
        echo "  * [$type_badge $epic — $plan_title]($company/specs/$epic/plan.md)"
      else
        echo "  * **$type_badge $epic**"
      fi

      # Tasks
      if [ -d "$epic_dir/tasks" ]; then
        for task_file in "$epic_dir/tasks/"*.md; do
          [ -f "$task_file" ] || continue
          task_name=$(basename "$task_file" .md)
          task_title=$(grep -m1 '^# ' "$task_file" 2>/dev/null | sed 's/^# //' || echo "$task_name")
          # Avoid duplicate prefix: if title already starts with task_name, use title only
          if echo "$task_title" | grep -q "^${task_name}[: ]"; then
            echo "    * [$task_title]($company/specs/$epic/tasks/$task_name.md)"
          else
            echo "    * [$task_name: $task_title]($company/specs/$epic/tasks/$task_name.md)"
          fi
        done
      fi
    done

    echo ""
  done

} > "$SIDEBAR"

echo "Generated: $SIDEBAR ($(grep -c '^\s*\*' "$SIDEBAR") entries)"
