#!/usr/bin/env bash
set -euo pipefail

# install-copilot-hooks.sh
#
# Installs git pre-commit and pre-push hooks that replicate
# Polaris's Claude Code deterministic PreToolUse gates.
#
# Idempotent: re-running updates hooks without duplication.
# Delegates to portable gate scripts in scripts/gates/*.sh.
#
# Usage:
#   bash scripts/install-copilot-hooks.sh            # install
#   bash scripts/install-copilot-hooks.sh --remove    # uninstall
#   bash scripts/install-copilot-hooks.sh --status    # check status

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
GIT_HOOKS_DIR="$ROOT_DIR/.git/hooks"

POLARIS_MARKER="# [polaris-copilot-hooks]"

ACTION="install"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --remove) ACTION="remove"; shift ;;
    --status) ACTION="status"; shift ;;
    -h|--help)
      echo "Usage: bash scripts/install-copilot-hooks.sh [--remove|--status]"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

# ---------------------------------------------------------------------------
# Hook content
# ---------------------------------------------------------------------------

PRE_COMMIT_HOOK='#!/usr/bin/env bash
'"$POLARIS_MARKER"'
# Auto-generated by scripts/install-copilot-hooks.sh
# Calls portable Polaris gate scripts for pre-commit validation.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
GATES_DIR="$REPO_ROOT/scripts/gates"

# Gate: scope-headers (keep inline — tiny, no standalone script needed)
if [[ -x "$REPO_ROOT/scripts/check-scope-headers.sh" ]]; then
  if ! "$REPO_ROOT/scripts/check-scope-headers.sh" --staged; then
    echo "[polaris pre-commit] ❌ Scope header validation failed." >&2
    exit 1
  fi
fi

# Gate: version-docs-lint
if [[ -x "$GATES_DIR/gate-version-lint.sh" ]]; then
  bash "$GATES_DIR/gate-version-lint.sh" --repo "$REPO_ROOT"
fi

# Gate: artifact-schema (task.md + refinement.json)
if [[ -x "$GATES_DIR/gate-artifact-schema.sh" ]]; then
  bash "$GATES_DIR/gate-artifact-schema.sh" --repo "$REPO_ROOT"
fi

# Gate: ci-local (run on commit too — cache makes reruns free)
if [[ -x "$GATES_DIR/gate-ci-local.sh" ]]; then
  bash "$GATES_DIR/gate-ci-local.sh" --repo "$REPO_ROOT"
fi
'

PRE_PUSH_HOOK='#!/usr/bin/env bash
'"$POLARIS_MARKER"'
# Auto-generated by scripts/install-copilot-hooks.sh
# Calls portable Polaris gate scripts for pre-push validation.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
GATES_DIR="$REPO_ROOT/scripts/gates"

# Gate: ci-local (push-mode: only task/fix branches)
if [[ -x "$GATES_DIR/gate-ci-local.sh" ]]; then
  bash "$GATES_DIR/gate-ci-local.sh" --repo "$REPO_ROOT" --push-mode
fi

# Gate: evidence (verification evidence must exist)
if [[ -x "$GATES_DIR/gate-evidence.sh" ]]; then
  bash "$GATES_DIR/gate-evidence.sh" --repo "$REPO_ROOT"
fi

# Gate: changeset (developer ticket branches only)
if [[ -x "$GATES_DIR/gate-changeset.sh" ]]; then
  bash "$GATES_DIR/gate-changeset.sh" --repo "$REPO_ROOT"
fi
'

# ---------------------------------------------------------------------------
# Actions
# ---------------------------------------------------------------------------

is_polaris_hook() {
  local file="$1"
  [[ -f "$file" ]] && head -5 "$file" | grep -qF "$POLARIS_MARKER" 2>/dev/null
}

install_hook() {
  local hook_name="$1"
  local hook_content="$2"
  local hook_file="$GIT_HOOKS_DIR/$hook_name"

  if [[ -f "$hook_file" ]]; then
    if is_polaris_hook "$hook_file"; then
      # Ours — overwrite
      echo "$hook_content" > "$hook_file"
      chmod +x "$hook_file"
      echo "  ✅ Updated $hook_name (Polaris hook replaced)"
    else
      # Not ours — don't clobber
      echo "  ⚠️  $hook_name already exists (non-Polaris). Skipped." >&2
      echo "     To override, remove $hook_file first."
      return 1
    fi
  else
    echo "$hook_content" > "$hook_file"
    chmod +x "$hook_file"
    echo "  ✅ Installed $hook_name"
  fi
}

remove_hook() {
  local hook_name="$1"
  local hook_file="$GIT_HOOKS_DIR/$hook_name"

  if is_polaris_hook "$hook_file"; then
    rm -f "$hook_file"
    echo "  ✅ Removed $hook_name"
  elif [[ -f "$hook_file" ]]; then
    echo "  ⚠️  $hook_name exists but is not a Polaris hook. Skipped."
  else
    echo "  - $hook_name not installed"
  fi
}

status_hook() {
  local hook_name="$1"
  local hook_file="$GIT_HOOKS_DIR/$hook_name"

  if is_polaris_hook "$hook_file"; then
    echo "  ✅ $hook_name — Polaris hook installed"
  elif [[ -f "$hook_file" ]]; then
    echo "  ⚠️  $hook_name — exists (non-Polaris)"
  else
    echo "  ❌ $hook_name — not installed"
  fi
}

case "$ACTION" in
  install)
    echo "Installing Polaris git hooks..."
    mkdir -p "$GIT_HOOKS_DIR"
    install_hook "pre-commit" "$PRE_COMMIT_HOOK"
    install_hook "pre-push" "$PRE_PUSH_HOOK"
    echo
    echo "Done. Hooks delegate to scripts/gates/*.sh gate scripts."
    echo "To remove: bash scripts/install-copilot-hooks.sh --remove"
    ;;
  remove)
    echo "Removing Polaris git hooks..."
    remove_hook "pre-commit"
    remove_hook "pre-push"
    echo "Done."
    ;;
  status)
    echo "Polaris git hook status:"
    status_hook "pre-commit"
    status_hook "pre-push"
    ;;
esac
