#!/usr/bin/env bash
set -euo pipefail

# install-copilot-hooks.sh
#
# Installs git pre-commit and pre-push hooks that replicate
# Polaris's Claude Code deterministic PreToolUse gates.
#
# Idempotent: re-running updates hooks without duplication.
# Delegates to existing scripts/check-*.sh and scripts/validate-*.sh.
#
# Usage:
#   bash scripts/install-copilot-hooks.sh            # install
#   bash scripts/install-copilot-hooks.sh --remove    # uninstall
#   bash scripts/install-copilot-hooks.sh --status    # check status

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
GIT_HOOKS_DIR="$ROOT_DIR/.git/hooks"

POLARIS_MARKER="# [polaris-copilot-hooks]"

ACTION="install"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --remove) ACTION="remove"; shift ;;
    --status) ACTION="status"; shift ;;
    -h|--help)
      echo "Usage: bash scripts/install-copilot-hooks.sh [--remove|--status]"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

# ---------------------------------------------------------------------------
# Hook content
# ---------------------------------------------------------------------------

PRE_COMMIT_HOOK='#!/usr/bin/env bash
'"$POLARIS_MARKER"'
# Auto-generated by scripts/install-copilot-hooks.sh
# Replicates Polaris Claude Code deterministic PreToolUse gates for git commit.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

# Gate 0: scope-headers — validate L2 company rules have Scope: headers
if [[ -x "$REPO_ROOT/scripts/check-scope-headers.sh" ]]; then
  if ! "$REPO_ROOT/scripts/check-scope-headers.sh" --staged; then
    echo "[polaris pre-commit] ❌ Scope header validation failed." >&2
    exit 1
  fi
fi

# Gate 1: version-docs-lint — if VERSION is staged, run readme-lint
if git diff --cached --name-only | grep -q "^VERSION$"; then
  if [[ -f "$REPO_ROOT/scripts/readme-lint.py" ]]; then
    echo "[polaris pre-commit] VERSION staged — running readme-lint..."
    if ! python3 "$REPO_ROOT/scripts/readme-lint.py"; then
      echo "[polaris pre-commit] ❌ readme-lint failed. Fix docs before committing." >&2
      exit 1
    fi
    echo "[polaris pre-commit] ✅ readme-lint passed."
  fi
fi

# Gate 2: validate task.md schemas for staged task files
while IFS= read -r staged_file; do
  case "$staged_file" in
    */tasks/T*.md)
      if [[ -f "$REPO_ROOT/scripts/validate-task-md.sh" ]]; then
        echo "[polaris pre-commit] Validating $staged_file..."
        if ! bash "$REPO_ROOT/scripts/validate-task-md.sh" "$REPO_ROOT/$staged_file"; then
          echo "[polaris pre-commit] ❌ task.md schema validation failed: $staged_file" >&2
          exit 1
        fi
      fi
      ;;
  esac
done < <(git diff --cached --name-only)

# Gate 3: validate refinement.json for staged refinement files
while IFS= read -r staged_file; do
  case "$staged_file" in
    */refinement.json)
      if [[ -f "$REPO_ROOT/scripts/validate-refinement-json.sh" ]]; then
        echo "[polaris pre-commit] Validating $staged_file..."
        if ! bash "$REPO_ROOT/scripts/validate-refinement-json.sh" "$REPO_ROOT/$staged_file"; then
          echo "[polaris pre-commit] ❌ refinement.json schema validation failed: $staged_file" >&2
          exit 1
        fi
      fi
      ;;
  esac
done < <(git diff --cached --name-only)

# Gate 4: validate task.md dependency DAG for staged specs directories
specs_dirs=()
while IFS= read -r staged_file; do
  case "$staged_file" in
    */tasks/T*.md)
      dir="$(dirname "$(dirname "$REPO_ROOT/$staged_file")")"
      if [[ -f "$REPO_ROOT/scripts/validate-task-md-deps.sh" ]] && \
         [[ ! " ${specs_dirs[*]:-} " =~ " $dir " ]]; then
        specs_dirs+=("$dir")
      fi
      ;;
  esac
done < <(git diff --cached --name-only)

for dir in "${specs_dirs[@]:-}"; do
  if [[ -n "$dir" ]]; then
    echo "[polaris pre-commit] Validating task.md dependency DAG in $dir..."
    if ! bash "$REPO_ROOT/scripts/validate-task-md-deps.sh" "$dir"; then
      echo "[polaris pre-commit] ❌ task.md dependency DAG invalid in $dir" >&2
      exit 1
    fi
  fi
done

exit 0
'

PRE_PUSH_HOOK='#!/usr/bin/env bash
'"$POLARIS_MARKER"'
# Auto-generated by scripts/install-copilot-hooks.sh
# Replicates Polaris Claude Code deterministic PreToolUse gates for git push.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
BRANCH="$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD)"

# Gate 1: ci-local — run local CI mirror if it exists (task/* and fix/* branches only)
case "$BRANCH" in
  task/*|fix/*)
    if [[ -f "$REPO_ROOT/scripts/ci-local.sh" ]]; then
      HEAD_SHA="$(git -C "$REPO_ROOT" rev-parse HEAD)"
      BRANCH_SLUG="${BRANCH//\//-}"
      CACHE_FILE="/tmp/polaris-ci-local-${BRANCH_SLUG}-${HEAD_SHA}.json"

      if [[ -f "$CACHE_FILE" ]]; then
        echo "[polaris pre-push] ✅ CI local cache hit — skipping."
      else
        echo "[polaris pre-push] Running local CI mirror..."
        if ! bash "$REPO_ROOT/scripts/ci-local.sh"; then
          echo "[polaris pre-push] ❌ Local CI failed. Fix before pushing." >&2
          exit 1
        fi
        echo "[polaris pre-push] ✅ CI local passed."
      fi
    fi
    ;;
esac

# Gate 2: quality gate marker check
MARKER_FILE="/tmp/.quality-gate-passed-${BRANCH}"
if [[ -f "$MARKER_FILE" ]]; then
  MARKER_AGE=$(( $(date +%s) - $(stat -f "%m" "$MARKER_FILE" 2>/dev/null || stat -c "%Y" "$MARKER_FILE" 2>/dev/null || echo 0) ))
  if (( MARKER_AGE > 86400 )); then
    echo "[polaris pre-push] ⚠️  Quality gate marker is stale (>24h). Consider re-running quality checks." >&2
    # Advisory only — do not block
  else
    echo "[polaris pre-push] ✅ Quality gate marker valid."
  fi
else
  echo "[polaris pre-push] ⚠️  No quality gate marker found. Consider running quality checks." >&2
  # Advisory on first push — do not block
fi

exit 0
'

# ---------------------------------------------------------------------------
# Actions
# ---------------------------------------------------------------------------

is_polaris_hook() {
  local file="$1"
  [[ -f "$file" ]] && head -5 "$file" | grep -qF "$POLARIS_MARKER" 2>/dev/null
}

install_hook() {
  local hook_name="$1"
  local hook_content="$2"
  local hook_file="$GIT_HOOKS_DIR/$hook_name"

  if [[ -f "$hook_file" ]]; then
    if is_polaris_hook "$hook_file"; then
      # Ours — overwrite
      echo "$hook_content" > "$hook_file"
      chmod +x "$hook_file"
      echo "  ✅ Updated $hook_name (Polaris hook replaced)"
    else
      # Not ours — don't clobber
      echo "  ⚠️  $hook_name already exists (non-Polaris). Skipped." >&2
      echo "     To override, remove $hook_file first."
      return 1
    fi
  else
    echo "$hook_content" > "$hook_file"
    chmod +x "$hook_file"
    echo "  ✅ Installed $hook_name"
  fi
}

remove_hook() {
  local hook_name="$1"
  local hook_file="$GIT_HOOKS_DIR/$hook_name"

  if is_polaris_hook "$hook_file"; then
    rm -f "$hook_file"
    echo "  ✅ Removed $hook_name"
  elif [[ -f "$hook_file" ]]; then
    echo "  ⚠️  $hook_name exists but is not a Polaris hook. Skipped."
  else
    echo "  - $hook_name not installed"
  fi
}

status_hook() {
  local hook_name="$1"
  local hook_file="$GIT_HOOKS_DIR/$hook_name"

  if is_polaris_hook "$hook_file"; then
    echo "  ✅ $hook_name — Polaris hook installed"
  elif [[ -f "$hook_file" ]]; then
    echo "  ⚠️  $hook_name — exists (non-Polaris)"
  else
    echo "  ❌ $hook_name — not installed"
  fi
}

case "$ACTION" in
  install)
    echo "Installing Polaris git hooks..."
    mkdir -p "$GIT_HOOKS_DIR"
    install_hook "pre-commit" "$PRE_COMMIT_HOOK"
    install_hook "pre-push" "$PRE_PUSH_HOOK"
    echo
    echo "Done. Hooks delegate to scripts/check-*.sh and scripts/validate-*.sh."
    echo "To remove: bash scripts/install-copilot-hooks.sh --remove"
    ;;
  remove)
    echo "Removing Polaris git hooks..."
    remove_hook "pre-commit"
    remove_hook "pre-push"
    echo "Done."
    ;;
  status)
    echo "Polaris git hook status:"
    status_hook "pre-commit"
    status_hook "pre-push"
    ;;
esac
