#!/usr/bin/env bash
set -euo pipefail

# install-copilot-hooks.sh
#
# Installs git pre-commit and pre-push hooks that replicate
# Polaris's Claude Code deterministic PreToolUse gates.
#
# Idempotent: re-running updates hooks without duplication.
# Delegates to portable gate scripts in scripts/gates/*.sh.
#
# Usage:
#   bash scripts/install-copilot-hooks.sh            # install
#   bash scripts/install-copilot-hooks.sh --remove    # uninstall
#   bash scripts/install-copilot-hooks.sh --status    # check status

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
GIT_HOOKS_DIR="$ROOT_DIR/.git/hooks"

POLARIS_MARKER="# [polaris-copilot-hooks]"

ACTION="install"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --remove) ACTION="remove"; shift ;;
    --status) ACTION="status"; shift ;;
    -h|--help)
      echo "Usage: bash scripts/install-copilot-hooks.sh [--remove|--status]"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

# ---------------------------------------------------------------------------
# Hook content
# ---------------------------------------------------------------------------

PRE_COMMIT_HOOK='#!/usr/bin/env bash
'"$POLARIS_MARKER"'
# Auto-generated by scripts/install-copilot-hooks.sh
# Calls portable Polaris gate scripts for pre-commit validation.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
GATES_DIR="$REPO_ROOT/scripts/gates"

# Gate: scope-headers (keep inline — tiny, no standalone script needed)
if [[ -x "$REPO_ROOT/scripts/check-scope-headers.sh" ]]; then
  if ! "$REPO_ROOT/scripts/check-scope-headers.sh" --staged; then
    echo "[polaris pre-commit] ❌ Scope header validation failed." >&2
    exit 1
  fi
fi

# Gate: version-docs-lint
if [[ -x "$GATES_DIR/gate-version-lint.sh" ]]; then
  bash "$GATES_DIR/gate-version-lint.sh" --repo "$REPO_ROOT"
fi

# Gate: no tracked docs-manager specs
if [[ -x "$GATES_DIR/gate-no-tracked-specs.sh" ]]; then
  bash "$GATES_DIR/gate-no-tracked-specs.sh" --repo "$REPO_ROOT"
fi

# Gate: artifact-schema (task.md + refinement.json + refinement inbox)
if [[ -x "$GATES_DIR/gate-artifact-schema.sh" ]]; then
  bash "$GATES_DIR/gate-artifact-schema.sh" --repo "$REPO_ROOT"
fi

# Gate: evidence producer whitelist (staged marker writers)
if [[ -x "$GATES_DIR/gate-evidence-producer-whitelist.sh" ]]; then
  bash "$GATES_DIR/gate-evidence-producer-whitelist.sh" --repo "$REPO_ROOT" --staged
fi

# Gate: ci-local (run on commit too — cache makes reruns free)
if [[ -x "$GATES_DIR/gate-ci-local.sh" ]]; then
  bash "$GATES_DIR/gate-ci-local.sh" --repo "$REPO_ROOT"
fi
'

PRE_PUSH_HOOK='#!/usr/bin/env bash
'"$POLARIS_MARKER"'
# Auto-generated by scripts/install-copilot-hooks.sh
# Calls portable Polaris gate scripts for pre-push validation.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
GATES_DIR="$REPO_ROOT/scripts/gates"

# Delete/tags carve-out (DP-305 D4): mirror the pre-push-quality-gate.sh
# --delete|--tags exemption. A git-native pre-push hook reads refs from STDIN
# (one per line: "<local_ref> <local_sha> <remote_ref> <remote_sha>"); for a
# deletion the local SHA is all-zeros (and the local ref is rendered "(delete)").
# Exit 0 BEFORE running any gate when EVERY ref in the push is a deletion, or
# EVERY ref is a tag. A content-bearing or mixed push falls through to the gates.
push_refs="$(cat || true)"
if [[ -n "$push_refs" ]]; then
  all_deletions=1
  all_tags=1
  saw_ref=0
  while read -r local_ref local_sha remote_ref _remote_sha _rest; do
    [[ -n "${local_ref:-}" ]] || continue
    saw_ref=1
    # deletion: local SHA is all-zeros, or git rendered the local ref "(delete)"
    if [[ "$local_ref" != "(delete)" && ! "${local_sha:-}" =~ ^0+$ ]]; then
      all_deletions=0
    fi
    # tag: the remote ref lives under refs/tags/
    if [[ "${remote_ref:-}" != refs/tags/* ]]; then
      all_tags=0
    fi
  done <<<"$push_refs"
  if [[ "$saw_ref" -eq 1 ]] && { [[ "$all_deletions" -eq 1 ]] || [[ "$all_tags" -eq 1 ]]; }; then
    exit 0
  fi
fi

# Gate: branch-name ASCII (DP-307 D4 / AC5). Reuse the single-source judgment in
# scripts/validate-branch-name-ascii.sh; do NOT re-implement the byte check here.
# Only runs for content-bearing pushes — the delete-only / tags-only carve-out
# above already exited (AC-NEG2). Each content-bearing local branch ref is
# checked; a non-ASCII name fails the push closed.
BRANCH_ASCII_VALIDATOR="$REPO_ROOT/scripts/validate-branch-name-ascii.sh"
if [[ -n "$push_refs" && -f "$BRANCH_ASCII_VALIDATOR" ]]; then
  while read -r local_ref local_sha _remote_ref _remote_sha _rest; do
    [[ -n "${local_ref:-}" ]] || continue
    # Skip deletions (zero local SHA / "(delete)") — they never carry content.
    [[ "$local_ref" == "(delete)" || "${local_sha:-}" =~ ^0+$ ]] && continue
    # Only branch refs carry a branch name; tags / other refs are not gated here.
    case "$local_ref" in
      refs/heads/*) bash "$BRANCH_ASCII_VALIDATOR" "${local_ref#refs/heads/}" ;;
    esac
  done <<<"$push_refs"
fi

# Gate: runtime-instruction manifest freshness (DP-320 D1 / AC2 / R1). The
# portable git hook deliberately does NOT branch-filter this check: a stale
# manifest pushed directly to main/develop must still be blocked (EC2). The gate
# is verdict-equivalent to compile-runtime-instructions.sh --check, so a fresh
# manifest passes on any branch and product repos without the compiler no-op.
if [[ -x "$GATES_DIR/gate-runtime-instruction-manifest.sh" ]]; then
  bash "$GATES_DIR/gate-runtime-instruction-manifest.sh" --repo "$REPO_ROOT"
fi

# Gate: ci-local (push-mode: only task/fix branches)
if [[ -x "$GATES_DIR/gate-ci-local.sh" ]]; then
  bash "$GATES_DIR/gate-ci-local.sh" --repo "$REPO_ROOT" --push-mode
fi

# Gate: no tracked docs-manager specs
if [[ -x "$GATES_DIR/gate-no-tracked-specs.sh" ]]; then
  bash "$GATES_DIR/gate-no-tracked-specs.sh" --repo "$REPO_ROOT"
fi

# Gate: template leaks (recurrence prevention for DP-228 — scan workspace
# tracked files for live company slug / JIRA prefix / Slack ID / internal URL
# before push, per rules/framework-iteration.md § Template-Facing Examples
# Must Be Generic).
if [[ -x "$GATES_DIR/gate-template-leaks.sh" ]]; then
  bash "$GATES_DIR/gate-template-leaks.sh" --repo "$REPO_ROOT"
fi

# Gate: evidence producer whitelist (changed marker writers)
if [[ -x "$GATES_DIR/gate-evidence-producer-whitelist.sh" ]]; then
  bash "$GATES_DIR/gate-evidence-producer-whitelist.sh" --repo "$REPO_ROOT"
fi

# Gate: revision-rebase (existing PR pushes only)
if [[ -x "$GATES_DIR/gate-revision-rebase.sh" ]]; then
  bash "$GATES_DIR/gate-revision-rebase.sh" --repo "$REPO_ROOT"
fi

# Gate: evidence (verification evidence must exist)
if [[ -x "$GATES_DIR/gate-evidence.sh" ]]; then
  bash "$GATES_DIR/gate-evidence.sh" --repo "$REPO_ROOT"
fi

# Gate: changeset (developer ticket branches only)
if [[ -x "$GATES_DIR/gate-changeset.sh" ]]; then
  bash "$GATES_DIR/gate-changeset.sh" --repo "$REPO_ROOT"
fi
'

# ---------------------------------------------------------------------------
# Actions
# ---------------------------------------------------------------------------

is_polaris_hook() {
  local file="$1"
  [[ -f "$file" ]] && head -5 "$file" | grep -qF "$POLARIS_MARKER" 2>/dev/null
}

install_hook() {
  local hook_name="$1"
  local hook_content="$2"
  local hook_file="$GIT_HOOKS_DIR/$hook_name"

  if [[ -f "$hook_file" ]]; then
    if is_polaris_hook "$hook_file"; then
      # Ours — overwrite
      echo "$hook_content" > "$hook_file"
      chmod +x "$hook_file"
      echo "  ✅ Updated $hook_name (Polaris hook replaced)"
    else
      # Not ours — don't clobber
      echo "  ⚠️  $hook_name already exists (non-Polaris). Skipped." >&2
      echo "     To override, remove $hook_file first."
      return 1
    fi
  else
    echo "$hook_content" > "$hook_file"
    chmod +x "$hook_file"
    echo "  ✅ Installed $hook_name"
  fi
}

remove_hook() {
  local hook_name="$1"
  local hook_file="$GIT_HOOKS_DIR/$hook_name"

  if is_polaris_hook "$hook_file"; then
    rm -f "$hook_file"
    echo "  ✅ Removed $hook_name"
  elif [[ -f "$hook_file" ]]; then
    echo "  ⚠️  $hook_name exists but is not a Polaris hook. Skipped."
  else
    echo "  - $hook_name not installed"
  fi
}

status_hook() {
  local hook_name="$1"
  local hook_file="$GIT_HOOKS_DIR/$hook_name"

  if is_polaris_hook "$hook_file"; then
    echo "  ✅ $hook_name — Polaris hook installed"
  elif [[ -f "$hook_file" ]]; then
    echo "  ⚠️  $hook_name — exists (non-Polaris)"
  else
    echo "  ❌ $hook_name — not installed"
  fi
}

case "$ACTION" in
  install)
    echo "Installing Polaris git hooks..."
    mkdir -p "$GIT_HOOKS_DIR"
    install_hook "pre-commit" "$PRE_COMMIT_HOOK"
    install_hook "pre-push" "$PRE_PUSH_HOOK"
    echo
    echo "Done. Hooks delegate to scripts/gates/*.sh gate scripts."
    echo "To remove: bash scripts/install-copilot-hooks.sh --remove"
    ;;
  remove)
    echo "Removing Polaris git hooks..."
    remove_hook "pre-commit"
    remove_hook "pre-push"
    echo "Done."
    ;;
  status)
    echo "Polaris git hook status:"
    status_hook "pre-commit"
    status_hook "pre-push"
    ;;
esac
