#!/usr/bin/env bash
# Synchronize spec lifecycle metadata with Starlight sidebar frontmatter.

set -euo pipefail

usage() {
  cat >&2 <<'EOF'
usage: sync-spec-sidebar-metadata.sh [--check|--apply] [file-or-directory...]

Default path:
  docs-manager/src/content/docs/specs

The script updates parent spec frontmatter for Starlight autogenerated sidebar:
  - Design Plans: normalized status, priority, sidebar label/order/badge
  - Company specs: sidebar badge aligned with parent status, preserving label/order
EOF
  exit 2
}

mode="check"
paths=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      mode="check"
      shift
      ;;
    --apply)
      mode="apply"
      shift
      ;;
    -h|--help)
      usage
      ;;
    -*)
      echo "error: unknown option: $1" >&2
      usage
      ;;
    *)
      paths+=("$1")
      shift
      ;;
  esac
done

if [[ ${#paths[@]} -eq 0 ]]; then
  paths=("docs-manager/src/content/docs/specs")
fi

case "$mode" in
  check|apply) ;;
  *) usage ;;
esac

python3 - "$mode" "${paths[@]}" <<'PY'
import re
import sys
from pathlib import Path

mode = sys.argv[1]
inputs = [Path(p) for p in sys.argv[2:]]

PARENT_DOC_NAMES = ["plan.md", "epic.md", "refinement.md", "breakdown.md", "README.md"]
COMPANY_ANCHOR_ORDER = ["refinement.md", "plan.md", "epic.md", "README.md"]
VALID_PRIORITIES = {"P0", "P1", "P2", "P3", "P4"}
STATUS_ALIASES = {
    "SEED": "SEEDED",
    "SEEDED": "SEEDED",
    "DISCUSSION": "DISCUSSION",
    "LOCKED": "LOCKED",
    "IMPLEMENTING": "IMPLEMENTING",
    "IMPLEMENTED": "IMPLEMENTED",
    "ABANDONED": "ABANDONED",
}
STATUS_PRIORITY = {
    "IMPLEMENTING": "P0",
    "LOCKED": "P1",
    "DISCUSSION": "P2",
    "SEEDED": "P3",
    "IMPLEMENTED": "P4",
    "ABANDONED": "P4",
}
STATUS_VARIANT = {
    "IMPLEMENTING": "caution",
    "LOCKED": "tip",
    "DISCUSSION": "note",
    "SEEDED": "note",
    "IMPLEMENTED": "success",
    "ABANDONED": "danger",
}


def fail(message: str, code: int = 1):
    print(f"error: {message}", file=sys.stderr)
    sys.exit(code)


def is_dp_dir(path: Path) -> bool:
    return path.name.startswith("DP-") and (
        path.parent.name == "design-plans"
        or (path.parent.name == "archive" and path.parent.parent.name == "design-plans")
    )


def is_company_ticket_dir(path: Path) -> bool:
    parts = path.parts
    if "companies" not in parts:
        return False
    idx = len(parts) - 1 - list(reversed(parts)).index("companies")
    rel = parts[idx + 1 :]
    if len(rel) == 2:
        return rel[1] != "archive"
    if len(rel) == 3:
        return rel[1] == "archive"
    return False


def anchor_for_container(path: Path):
    if is_dp_dir(path):
        candidate = path / "plan.md"
        return candidate if candidate.exists() else None
    if is_company_ticket_dir(path):
        for name in COMPANY_ANCHOR_ORDER:
            candidate = path / name
            if candidate.exists():
                return candidate
    return None


def parent_files(path: Path):
    if not path.exists():
        fail(f"path not found: {path}", 2)
    if path.is_file():
        if path.name in PARENT_DOC_NAMES:
            yield path
        return

    direct = anchor_for_container(path)
    if direct:
        yield direct
        return

    for file in sorted(path.rglob("*.md")):
        if file.name not in PARENT_DOC_NAMES:
            continue
        if anchor_for_container(file.parent) == file:
            yield file


def split_frontmatter(text: str, path: Path):
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path}: missing YAML frontmatter")
    end = None
    for idx in range(1, len(lines)):
        if lines[idx].strip() == "---":
            end = idx
            break
    if end is None:
        raise ValueError(f"{path}: unterminated YAML frontmatter")
    return lines[1:end], lines[end:]


def strip_quotes(value: str) -> str:
    value = value.strip()
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        return value[1:-1]
    return value


def quote_yaml(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def frontmatter_value(lines, key):
    pattern = re.compile(rf"^{re.escape(key)}:\s*(.*?)\s*$")
    for line in lines:
        match = pattern.match(line)
        if match:
            return strip_quotes(match.group(1))
    return None


def sidebar_value(lines, key):
    in_sidebar = False
    pattern = re.compile(rf"^\s{{2}}{re.escape(key)}:\s*(.*?)\s*$")
    for line in lines:
        if line.startswith("sidebar:"):
            in_sidebar = True
            continue
        if in_sidebar and line and not line.startswith((" ", "\t")):
            break
        if in_sidebar:
            match = pattern.match(line)
            if match:
                return strip_quotes(match.group(1))
    return None


def remove_block(lines, key):
    output = []
    idx = 0
    prefix = f"{key}:"
    while idx < len(lines):
        line = lines[idx]
        if line.startswith(prefix):
            idx += 1
            while idx < len(lines):
                candidate = lines[idx]
                if candidate.startswith((" ", "\t")) or not candidate.strip():
                    idx += 1
                    continue
                break
            continue
        output.append(line)
        idx += 1
    return output


def upsert_scalar(lines, key, value):
    rendered = f"{key}: {value}\n"
    pattern = re.compile(rf"^{re.escape(key)}:\s*")
    for idx, line in enumerate(lines):
        if pattern.match(line):
            lines[idx] = rendered
            return
    insert_at = len(lines)
    for idx, line in enumerate(lines):
        if line.startswith("sidebar:"):
            insert_at = idx
            break
    lines.insert(insert_at, rendered)


def dp_number(path: Path):
    for part in reversed(path.parts):
        match = re.match(r"DP-(\d+)", part)
        if match:
            return int(match.group(1)), f"DP-{match.group(1)}"
    raise ValueError(f"{path}: cannot infer DP number from path")


def title_from_slug(path: Path):
    slug = re.sub(r"^DP-\d+-?", "", path.parent.name)
    return slug.replace("-", " ").strip()


def dp_sidebar_label(path: Path, title: str):
    _, dp_id = dp_number(path)
    clean = title.strip() or title_from_slug(path)
    clean = re.sub(r"\s+[—-]\s+Design Plan$", "", clean).strip()
    if clean == "Plan":
        clean = title_from_slug(path)
    if clean.startswith(dp_id):
        return clean
    return f"{dp_id}: {clean}"


def normalize_status(raw_status: str, path: Path):
    if not raw_status:
        raise ValueError(f"{path}: missing status")
    key = raw_status.strip().upper()
    if key not in STATUS_ALIASES:
        raise ValueError(f"{path}: unsupported status {raw_status!r}")
    return STATUS_ALIASES[key]


def normalize_priority(raw_priority: str | None, status: str, path: Path):
    if not raw_priority:
        return STATUS_PRIORITY[status]
    priority = raw_priority.strip().upper()
    if priority not in VALID_PRIORITIES:
        raise ValueError(f"{path}: unsupported priority {raw_priority!r}")
    return priority


def expected_text(path: Path):
    text = path.read_text(encoding="utf-8")
    fm_lines, rest = split_frontmatter(text, path)
    status = normalize_status(frontmatter_value(fm_lines, "status"), path)
    title = frontmatter_value(fm_lines, "title") or ""
    existing_label = sidebar_value(fm_lines, "label")
    existing_order = sidebar_value(fm_lines, "order")

    lines = remove_block(fm_lines, "sidebar")
    upsert_scalar(lines, "status", status)

    if lines and lines[-1].strip():
        lines.append("\n")

    if is_dp_dir(path.parent):
        priority = normalize_priority(frontmatter_value(fm_lines, "priority"), status, path)
        order, _ = dp_number(path)
        upsert_scalar(lines, "priority", priority)
        if lines and lines[-1].strip():
            lines.append("\n")
        lines.extend(
            [
                "sidebar:\n",
                f"  label: {quote_yaml(dp_sidebar_label(path, title))}\n",
                f"  order: {order}\n",
                "  badge:\n",
                f"    text: {quote_yaml(f'{status} / {priority}')}\n",
                f"    variant: {quote_yaml(STATUS_VARIANT[status])}\n",
            ]
        )
    else:
        lines.append("sidebar:\n")
        if existing_label:
            lines.append(f"  label: {quote_yaml(existing_label)}\n")
        if existing_order:
            lines.append(f"  order: {existing_order}\n")
        lines.extend(
            [
                "  badge:\n",
                f"    text: {quote_yaml(status)}\n",
                f"    variant: {quote_yaml(STATUS_VARIANT[status])}\n",
            ]
        )

    return "---\n" + "".join(lines) + "".join(rest)


seen = set()
files = []
for input_path in inputs:
    for file in parent_files(input_path):
        resolved = file.resolve()
        if resolved not in seen:
            seen.add(resolved)
            files.append(file)

if not files:
    fail("no parent spec metadata files found", 2)

changed = []
errors = []
for file in files:
    try:
        current = file.read_text(encoding="utf-8")
        expected = expected_text(file)
    except Exception as exc:
        errors.append(str(exc))
        continue
    if current != expected:
        changed.append(file)
        if mode == "apply":
            file.write_text(expected, encoding="utf-8")

for error in errors:
    print(f"error: {error}", file=sys.stderr)

if errors:
    sys.exit(1)

if changed:
    for file in changed:
        print(f"{'updated' if mode == 'apply' else 'would update'}: {file}")
    if mode == "check":
        sys.exit(1)

print(f"PASS: spec sidebar metadata {mode} ({len(files)} file(s), {len(changed)} changed)")
PY
