#!/usr/bin/env bash
# Synchronize Design Plan lifecycle metadata with Starlight sidebar frontmatter.

set -euo pipefail

usage() {
  cat >&2 <<'EOF'
usage: sync-dp-sidebar-metadata.sh [--check|--apply] [file-or-directory...]

Default path:
  docs-manager/src/content/docs/specs/design-plans

The script updates Design Plan plan.md frontmatter with:
  - normalized status values (SEED -> SEEDED)
  - priority when missing
  - sidebar.label/order/badge metadata for Starlight autogenerated sidebar links
EOF
  exit 2
}

mode="check"
paths=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      mode="check"
      shift
      ;;
    --apply)
      mode="apply"
      shift
      ;;
    -h|--help)
      usage
      ;;
    -*)
      echo "error: unknown option: $1" >&2
      usage
      ;;
    *)
      paths+=("$1")
      shift
      ;;
  esac
done

if [[ ${#paths[@]} -eq 0 ]]; then
  paths=("docs-manager/src/content/docs/specs/design-plans")
fi

case "$mode" in
  check|apply) ;;
  *) usage ;;
esac

python3 - "$mode" "${paths[@]}" <<'PY'
import re
import sys
from pathlib import Path

mode = sys.argv[1]
inputs = [Path(p) for p in sys.argv[2:]]

VALID_STATUSES = {"SEEDED", "DISCUSSION", "LOCKED", "IMPLEMENTING", "IMPLEMENTED", "ABANDONED"}
VALID_PRIORITIES = {"P0", "P1", "P2", "P3", "P4"}
STATUS_ALIASES = {
    "SEED": "SEEDED",
    "SEEDED": "SEEDED",
    "DISCUSSION": "DISCUSSION",
    "LOCKED": "LOCKED",
    "IMPLEMENTING": "IMPLEMENTING",
    "IMPLEMENTED": "IMPLEMENTED",
    "ABANDONED": "ABANDONED",
}
STATUS_PRIORITY = {
    "IMPLEMENTING": "P0",
    "LOCKED": "P1",
    "DISCUSSION": "P2",
    "SEEDED": "P3",
    "IMPLEMENTED": "P4",
    "ABANDONED": "P4",
}
STATUS_VARIANT = {
    "IMPLEMENTING": "caution",
    "LOCKED": "tip",
    "DISCUSSION": "note",
    "SEEDED": "note",
    "IMPLEMENTED": "success",
    "ABANDONED": "danger",
}


def plan_files(path: Path):
    if not path.exists():
        print(f"error: path not found: {path}", file=sys.stderr)
        sys.exit(2)
    if path.is_file():
        if path.name == "plan.md":
            yield path
        return
    for file in sorted(path.rglob("plan.md")):
        if "/design-plans/" in file.as_posix() or file.as_posix().endswith("/design-plans/plan.md"):
            yield file


def split_frontmatter(text: str, path: Path):
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        raise ValueError(f"{path}: missing YAML frontmatter")
    end = None
    for idx in range(1, len(lines)):
        if lines[idx].strip() == "---":
            end = idx
            break
    if end is None:
        raise ValueError(f"{path}: unterminated YAML frontmatter")
    return lines[1:end], lines[end:]


def strip_quotes(value: str) -> str:
    value = value.strip()
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        return value[1:-1]
    return value


def quote_yaml(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def frontmatter_value(lines, key):
    pattern = re.compile(rf"^{re.escape(key)}:\s*(.*?)\s*$")
    for line in lines:
        match = pattern.match(line)
        if match:
            return strip_quotes(match.group(1))
    return None


def remove_block(lines, key):
    output = []
    idx = 0
    prefix = f"{key}:"
    while idx < len(lines):
        line = lines[idx]
        if line.startswith(prefix):
            idx += 1
            while idx < len(lines):
                candidate = lines[idx]
                if candidate.startswith((" ", "\t")) or not candidate.strip():
                    idx += 1
                    continue
                break
            continue
        output.append(line)
        idx += 1
    return output


def upsert_scalar(lines, key, value):
    rendered = f"{key}: {value}\n"
    pattern = re.compile(rf"^{re.escape(key)}:\s*")
    for idx, line in enumerate(lines):
        if pattern.match(line):
            lines[idx] = rendered
            return
    insert_at = len(lines)
    for idx, line in enumerate(lines):
        if line.startswith("sidebar:"):
            insert_at = idx
            break
    lines.insert(insert_at, rendered)


def dp_number(path: Path):
    for part in reversed(path.parts):
        match = re.match(r"DP-(\d+)", part)
        if match:
            return int(match.group(1)), f"DP-{match.group(1)}"
    raise ValueError(f"{path}: cannot infer DP number from path")


def title_from_slug(path: Path):
    dp_dir = path.parent.name
    slug = re.sub(r"^DP-\d+-?", "", dp_dir)
    return slug.replace("-", " ").strip()


def sidebar_label(path: Path, title: str):
    _, dp_id = dp_number(path)
    clean = title.strip() or title_from_slug(path)
    clean = re.sub(r"\s+[—-]\s+Design Plan$", "", clean).strip()
    if clean == "Plan":
        clean = title_from_slug(path)
    if clean.startswith(dp_id):
        return clean
    return f"{dp_id}: {clean}"


def normalize_status(raw_status: str, path: Path):
    if not raw_status:
        raise ValueError(f"{path}: missing status")
    key = raw_status.strip().upper()
    if key not in STATUS_ALIASES:
        raise ValueError(f"{path}: unsupported status {raw_status!r}")
    return STATUS_ALIASES[key]


def normalize_priority(raw_priority: str | None, status: str, path: Path):
    if not raw_priority:
        return STATUS_PRIORITY[status]
    priority = raw_priority.strip().upper()
    if priority not in VALID_PRIORITIES:
        raise ValueError(f"{path}: unsupported priority {raw_priority!r}")
    return priority


def expected_text(path: Path):
    text = path.read_text(encoding="utf-8")
    fm_lines, rest = split_frontmatter(text, path)
    title = frontmatter_value(fm_lines, "title") or ""
    status = normalize_status(frontmatter_value(fm_lines, "status"), path)
    priority = normalize_priority(frontmatter_value(fm_lines, "priority"), status, path)
    order, _ = dp_number(path)

    lines = remove_block(fm_lines, "sidebar")
    upsert_scalar(lines, "status", status)
    upsert_scalar(lines, "priority", priority)

    if lines and lines[-1].strip():
        lines.append("\n")
    lines.extend(
        [
            "sidebar:\n",
            f"  label: {quote_yaml(sidebar_label(path, title))}\n",
            f"  order: {order}\n",
            "  badge:\n",
            f"    text: {quote_yaml(f'{status} / {priority}')}\n",
            f"    variant: {quote_yaml(STATUS_VARIANT[status])}\n",
        ]
    )

    return "---\n" + "".join(lines) + "".join(rest)


seen = set()
files = []
for input_path in inputs:
    for file in plan_files(input_path):
        resolved = file.resolve()
        if resolved not in seen:
            seen.add(resolved)
            files.append(file)

if not files:
    print("error: no Design Plan plan.md files found", file=sys.stderr)
    sys.exit(2)

changed = []
errors = []
for file in files:
    try:
        current = file.read_text(encoding="utf-8")
        expected = expected_text(file)
    except Exception as exc:
        errors.append(str(exc))
        continue
    if current != expected:
        changed.append(file)
        if mode == "apply":
            file.write_text(expected, encoding="utf-8")

for error in errors:
    print(f"error: {error}", file=sys.stderr)

if errors:
    sys.exit(1)

if changed:
    for file in changed:
        print(f"{'updated' if mode == 'apply' else 'would update'}: {file}")
    if mode == "check":
        sys.exit(1)

print(f"PASS: DP sidebar metadata {mode} ({len(files)} file(s), {len(changed)} changed)")
PY
