#!/usr/bin/env bash
set -euo pipefail

# transpile-to-copilot.sh
#
# Source of truth: .claude/rules/*.md (L1 universal only)
# Generated target: .github/copilot-instructions.md (+ manifest)
#
# Usage:
#   bash scripts/transpile-to-copilot.sh            # apply
#   bash scripts/transpile-to-copilot.sh --check    # verify no drift

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

CLAUDE_RULES_DIR="$ROOT_DIR/.claude/rules"
GITHUB_DIR="$ROOT_DIR/.github"
GENERATED_DIR="$GITHUB_DIR/.generated"
TARGET_INSTRUCTIONS="$GITHUB_DIR/copilot-instructions.md"
TARGET_MANIFEST="$GENERATED_DIR/copilot-rules-manifest.txt"

CHECK_ONLY=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK_ONLY=true; shift ;;
    -h|--help)
      sed -n '1,10p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

[[ -d "$CLAUDE_RULES_DIR" ]] || {
  echo "Missing source rules directory: $CLAUDE_RULES_DIR" >&2
  exit 1
}

tmp_instructions="$(mktemp)"
tmp_manifest="$(mktemp)"
trap 'rm -f "$tmp_instructions" "$tmp_manifest"' EXIT

# ---------------------------------------------------------------------------
# Build SHA256 manifest (L1 rules only — skip company subdirectories)
# ---------------------------------------------------------------------------
while IFS= read -r f; do
  rel="${f#"$ROOT_DIR"/}"
  sha="$(shasum -a 256 "$f" | awk '{print $1}')"
  printf '%s  %s\n' "$sha" "$rel" >> "$tmp_manifest"
done < <(find "$CLAUDE_RULES_DIR" -maxdepth 1 -type f -name '*.md' | sort)

# ---------------------------------------------------------------------------
# Preamble — static Copilot-specific context
# ---------------------------------------------------------------------------
cat > "$tmp_instructions" << 'PREAMBLE'
# Copilot Instructions — Polaris Workspace

> Auto-generated by `scripts/transpile-to-copilot.sh`.
> Source of truth: `.claude/rules/*.md` — do not edit the Rules section manually.
>
> Regenerate: `bash scripts/transpile-to-copilot.sh`
> Check drift: `bash scripts/transpile-to-copilot.sh --check`

## What This Repo Is

**Polaris** is a [Claude Code](https://docs.anthropic.com/en/docs/claude-code) workspace template that acts as an AI strategist. It routes tasks to specialized **skills**, learns from corrections, and evolves its own rules. The repo is used as a live working instance — not just a static template.

Three pillars:
1. **Development Assistance** — JIRA ticket → branch → code → PR, fully automated
2. **Self-Learning** — corrections are promoted to permanent rules; insights persist cross-session
3. **Daily Operations** — standup, sprint planning, worklog

## Architecture

```
~/work/                          ← workspace root (this repo)
├── CLAUDE.md                    ← AI strategist persona + routing rules
├── workspace-config.yaml        ← routes JIRA keys and company names
├── VERSION                      ← semver; bump triggers auto-sync to template
├── .claude/
│   ├── rules/                   ← L1 universal rules (auto-loaded every session)
│   │   └── {company}/           ← L2 company-specific rules (scope-gated)
│   ├── skills/                  ← 26+ workflow skill definitions (SKILL.md per skill)
│   │   └── references/          ← shared reference docs consumed by skills
│   ├── handbook/                ← user working preferences and quality standards
│   └── hooks/                   ← PreToolUse / PostToolUse Claude Code hooks
├── scripts/                     ← shell + Python automation scripts
├── _template/                   ← rule and config templates for /init
└── {company}/                   ← created by /init; gitignored company workspace
    └── workspace-config.yaml    ← JIRA project keys, Slack, repo mappings
```

## Key Scripts

```bash
# Transpile rules for multi-AI parity
scripts/transpile-to-copilot.sh          # → .github/copilot-instructions.md
scripts/transpile-rules-to-codex.sh      # → .codex/AGENTS.md

# Install git hooks (replicate Claude Code deterministic gates)
scripts/install-copilot-hooks.sh

# Framework operations
scripts/sync-to-polaris.sh --push        # push framework changes to template
scripts/sync-from-polaris.sh             # pull upstream template changes
```

## Copilot-Specific: Pre-Check Protocol

Claude Code uses PreToolUse hooks to intercept and block dangerous commands *before* execution. Copilot CLI has no hook system, so the equivalent is a **pre-check pattern**: run the validation script yourself, check its exit code, then decide whether to proceed.

### Deterministic Gates (Pre-Commit)

Before running `git commit`, execute these checks:

| Gate | Script | What it validates |
|------|--------|-------------------|
| Version docs lint | `scripts/check-version-bump-reminder.sh` | If VERSION staged, run readme-lint |
| Task.md schema | `scripts/validate-task-md.sh {path}` | Required sections present |
| Refinement schema | `scripts/validate-refinement-json.sh {path}` | Required fields in refinement.json |
| Refinement inbox schema | `scripts/validate-refinement-inbox-record.sh {path}` | breakdown-produced return inbox has no raw sidecar evidence |
| Task.md deps | `scripts/validate-task-md-deps.sh {dir}` | Dependencies form valid DAG |

### Deterministic Gates (Pre-Push)

Before running `git push`, execute these checks:

| Gate | Script | What it validates |
|------|--------|-------------------|
| CI local | `.claude/scripts/ci-local.sh` (repo-specific, gitignored) | Local CI mirror passes |
| Quality gate | Check `/tmp/.quality-gate-passed-{branch}` | Quality check flow completed |
| Base freshness | `scripts/check-base-fresh.sh --task-md {path}` | Target base branch is recent |

### Deterministic Gates (Pre-PR)

Before running `gh pr create`, execute:

| Gate | Script | What it validates |
|------|--------|-------------------|
| PR base branch | `scripts/resolve-task-base.sh` + compare | `--base` matches task.md expected base |

### Bash Command Rules (Always)

Before running any bash command, self-check:

| Gate | Script | What it validates |
|------|--------|-------------------|
| No `cd` | `scripts/check-no-cd-in-bash.sh --command "..."` | No `cd path && cmd` pattern |
| No independent chaining | `scripts/check-no-independent-cmd-chaining.sh --command "..."` | No `cmd1; cmd2` where cmd2 is independent |

**Exit code convention**: `0` = pass, `1` = retryable error, `2` = hard block (do not proceed).

### Git Hooks

If `scripts/install-copilot-hooks.sh` has been run, the pre-commit and pre-push gates above are enforced automatically by git. The bash command gates (no-cd, no-chaining) remain LLM self-discipline.

## Copilot-Specific: Session Wrap-Up

Claude Code has Stop hooks that fire at session end. In Copilot, achieve the same by explicitly wrapping up before ending:

1. **Check todos** — review all pending tasks; carry forward or close
2. **Session summary** — if substantial work was done, note what was accomplished
3. **Feedback reflection** — if you self-corrected during the session, consider whether it should become a permanent rule

Trigger: user says "收工", "wrap up", "EOD", or "session complete".

## Copilot-Specific: Known Limitations vs Claude Code

| Feature | Claude Code | Copilot CLI | Mitigation |
|---------|------------|------------|------------|
| PreToolUse hooks | Physical blocks (exit 2) | Git hooks + LLM pre-check | Covered above |
| Context compression | PreCompact/PostCompact hooks | Not applicable | Copilot uses larger context windows |
| Stop hooks | Auto-fire at turn end | User-triggered wrap-up | See Session Wrap-Up above |
| Memory hot-tier injection | Auto-loaded every session | Read `memory/` manually on context switch | Ask: "load memory for {topic}" |
| Skill tool | Platform-native routing | Available via Copilot skill tool | Same functionality |

## Conventions

### Skill-First Routing
When a user message matches a skill's trigger pattern, invoke the **Skill tool immediately** — before reading any files, calling any APIs, or running any commands. Skills define their own data-fetching and delegation.

Full routing table: `.claude/rules/skill-routing.md`

### Branch Switching → Always Use Worktrees
Any operation that changes `HEAD`, switches branches, or touches the working tree must run in a `git worktree add` copy instead.

Worktree path convention: `{base_dir}/.worktrees/{repo}-{purpose}-{ticket_or_topic}`

### Bash Commands — No `cd`
Never use `cd <path> && <cmd>`. Use each tool's built-in path parameter.
Independent commands should be issued as parallel tool calls, not chained with `&&`.

### Rules Hierarchy
- **L1** (`.claude/rules/*.md`) — universal, always loaded
- **L2** (`.claude/rules/{company}/*.md`) — company-specific, scope-gated

### Secrets
`.env` is tracked — declare variable names only, leave values empty. Real values go in `.env.local` (gitignored).

### Version Bump → Auto-Sync
After any commit that changes `VERSION`, run `scripts/sync-to-polaris.sh --push`.

## MCP Dependencies

Required for full skill coverage:
- **Atlassian MCP** — JIRA and Confluence
- **Slack MCP** — standup, review-inbox, check-pr-approvals

Optional:
- **Google Calendar MCP** — meeting context for standup
- **Figma MCP** — when tickets reference Figma designs

PREAMBLE

# ---------------------------------------------------------------------------
# Append L1 rules (universal only — skip company subdirectories)
# ---------------------------------------------------------------------------
{
  echo
  echo "---"
  echo
  echo "## Rules (Transpiled from .claude/rules/)"
  echo
} >> "$tmp_instructions"

while IFS= read -r f; do
  rel="${f#"$ROOT_DIR"/}"
  printf '### `%s`\n\n' "$rel" >> "$tmp_instructions"
  cat "$f" >> "$tmp_instructions"
  printf '\n\n' >> "$tmp_instructions"
done < <(find "$CLAUDE_RULES_DIR" -maxdepth 1 -type f -name '*.md' | sort)
perl -0pi -e 's/\n+\z/\n/' "$tmp_instructions"

# ---------------------------------------------------------------------------
# Check mode: compare against existing generated files
# ---------------------------------------------------------------------------
if [[ "$CHECK_ONLY" == true ]]; then
  if [[ ! -f "$TARGET_INSTRUCTIONS" || ! -f "$TARGET_MANIFEST" ]]; then
    echo "DRIFT: generated Copilot files are missing. Run transpile first." >&2
    exit 1
  fi
  if ! diff -q "$tmp_instructions" "$TARGET_INSTRUCTIONS" >/dev/null 2>&1; then
    echo "DRIFT: $TARGET_INSTRUCTIONS is out of date." >&2
    diff -u "$TARGET_INSTRUCTIONS" "$tmp_instructions" | head -30 >&2
    exit 1
  fi
  if ! diff -q "$tmp_manifest" "$TARGET_MANIFEST" >/dev/null 2>&1; then
    echo "DRIFT: $TARGET_MANIFEST is out of date." >&2
    exit 1
  fi
  echo "OK: Copilot generated instruction files are in sync."
  exit 0
fi

# ---------------------------------------------------------------------------
# Write mode: generate files
# ---------------------------------------------------------------------------
mkdir -p "$GITHUB_DIR" "$GENERATED_DIR"
cp "$tmp_instructions" "$TARGET_INSTRUCTIONS"
cp "$tmp_manifest" "$TARGET_MANIFEST"
echo "Generated:"
echo "  - $TARGET_INSTRUCTIONS"
echo "  - $TARGET_MANIFEST"
