#!/usr/bin/env bash
set -euo pipefail

# transpile-rules-to-codex.sh
#
# Source of truth: .claude/rules/*.md
# Generated target: .codex/AGENTS.md (+ manifest)
#
# Usage:
#   bash scripts/transpile-rules-to-codex.sh            # apply
#   bash scripts/transpile-rules-to-codex.sh --check    # verify no drift

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

CLAUDE_RULES_DIR="$ROOT_DIR/.claude/rules"
CODEX_DIR="$ROOT_DIR/.codex"
GENERATED_DIR="$CODEX_DIR/.generated"
TARGET_AGENTS="$CODEX_DIR/AGENTS.md"
TARGET_MANIFEST="$GENERATED_DIR/rules-manifest.txt"

CHECK_ONLY=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK_ONLY=true; shift ;;
    -h|--help)
      sed -n '1,20p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

[[ -d "$CLAUDE_RULES_DIR" ]] || {
  echo "Missing source rules directory: $CLAUDE_RULES_DIR" >&2
  exit 1
}

tmp_agents="$(mktemp)"
tmp_manifest="$(mktemp)"
trap 'rm -f "$tmp_agents" "$tmp_manifest"' EXIT

while IFS= read -r f; do
  rel="${f#"$ROOT_DIR"/}"
  sha="$(shasum -a 256 "$f" | awk '{print $1}')"
  printf '%s  %s\n' "$sha" "$rel" >> "$tmp_manifest"
done < <(find "$CLAUDE_RULES_DIR" -type f -name '*.md' | sort)

{
  echo "# AGENTS"
  echo
  echo "> Auto-generated by \`scripts/transpile-rules-to-codex.sh\`."
  echo "> Do not edit this file manually."
  echo
  echo "Source of truth: \`.claude/rules/**/*.md\`"
  echo
  echo "## Usage"
  echo
  echo "- Apply updates: \`bash scripts/transpile-rules-to-codex.sh\`"
  echo "- Check drift: \`bash scripts/transpile-rules-to-codex.sh --check\`"
  echo
  echo "## Rules (Mirrored From .claude/rules)"
  echo
} > "$tmp_agents"

while IFS= read -r f; do
  rel="${f#"$ROOT_DIR"/}"
  printf '### `%s`\n\n' "$rel" >> "$tmp_agents"
  cat "$f" >> "$tmp_agents"
  printf '\n\n' >> "$tmp_agents"
done < <(find "$CLAUDE_RULES_DIR" -type f -name '*.md' | sort)

if [[ "$CHECK_ONLY" == true ]]; then
  if [[ ! -f "$TARGET_AGENTS" || ! -f "$TARGET_MANIFEST" ]]; then
    echo "DRIFT: generated Codex files are missing. Run transpile first." >&2
    exit 1
  fi
  if ! diff -q "$tmp_agents" "$TARGET_AGENTS" >/dev/null 2>&1; then
    echo "DRIFT: $TARGET_AGENTS is out of date." >&2
    exit 1
  fi
  if ! diff -q "$tmp_manifest" "$TARGET_MANIFEST" >/dev/null 2>&1; then
    echo "DRIFT: $TARGET_MANIFEST is out of date." >&2
    exit 1
  fi
  echo "OK: Codex generated rule files are in sync."
  exit 0
fi

mkdir -p "$CODEX_DIR" "$GENERATED_DIR"
cp "$tmp_agents" "$TARGET_AGENTS"
cp "$tmp_manifest" "$TARGET_MANIFEST"
echo "Generated:"
echo "  - $TARGET_AGENTS"
echo "  - $TARGET_MANIFEST"

