#!/usr/bin/env bash
# Purpose: Fail closed when a newly committed generated-artifact candidate is
# not a registered interface with a freshness gate wired into a blocking lane.
# Inputs: --root <repo>, --base <git-ref>, --manifest <json> (all optional).
# Outputs: PASS summary or POLARIS_GENERATED_ARTIFACT_DISCIPLINE_BLOCKED markers.
set -euo pipefail

ROOT_DIR=""
BASE_REF="${POLARIS_FRAMEWORK_PR_BASE:-}"
MANIFEST_PATH=""

usage() {
  cat <<'USAGE'
Usage: bash scripts/validate-generated-artifact-discipline.sh \
  [--root <repo>] [--base <git-ref>] [--manifest <path>]

Enumerates files added in <base>...HEAD that either contain a `Generated by`
header or live under a `.generated/` directory. Every candidate must match an
exact scripts/manifest.json generated_artifact_interfaces[] row whose declared
freshness gate is wired at its declared blocking entrypoint.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      ROOT_DIR="${2:-}"
      shift 2
      ;;
    --base)
      BASE_REF="${2:-}"
      shift 2
      ;;
    --manifest)
      MANIFEST_PATH="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "validate-generated-artifact-discipline: unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$ROOT_DIR" ]]; then
  ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
if [[ -z "$MANIFEST_PATH" ]]; then
  MANIFEST_PATH="$ROOT_DIR/scripts/manifest.json"
fi

python3 "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/validate_generated_artifact_discipline_1.py" "$ROOT_DIR" "$BASE_REF" "$MANIFEST_PATH"
